### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#101]
The examples in the current annex should be validated as consistent with text of spec plus I suggest we have more of them. I threw in some query openc2 profile/schema/version examples but I think it would be nice to have examples of many commands and many targets - ideally every action in at least one example, every target in at least one example, every arg in at least one example, an example of at least one actuator with multiple profiles, and an example of at least one 'extension' (or 'data import'). And in an even more ideal world, the sections were actions/targets/args are defined would include something like "an example of the ip-connection target can be found in example 17 in Annex 1". We don't necessarily have to reach ideal, but we need more than we have currently.

**Comment by romanojd** [comment]
More examples have been added in an annex and within the body of the document if it was warranted.
