### ISSUE TITLE
Replace Core Actuator Profile

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#104]
Remove Section 4, Core Actuator Profile
Put in place a SHALL requiring all actuators to respond to query openc2 command.

**Comment by aracnid** [comment]
Section 4, "Core Actuator Profile" was replaced with "Mandatory Commands/Responses".

**Comment by romanojd** [comment]
Section 4, "Core Actuator Profile" was replaced with "Mandatory Commands/Responses".
