### ISSUE TITLE
Verify references and hyperlinks

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#127]
LS-001 (https://lists.oasis-open.org/archives/openc2-comment/201811/msg00001.html):
> (PDF page 8 line 22) In section 1.5.1, the reference to section 1.4 should refer to either 1.2 or 1.3. (1.2 is probably better).

LS-002 (https://lists.oasis-open.org/archives/openc2-comment/201811/msg00001.html):
> There are a number of opportunities for hyperlinked cross-references among sections in this document, which would likely be helpful to readers.

**Comment by romanojd** [comment]
The references and hyperlinks are updated in pull request #270. I'll make another pull request that applies the same approach to the rest of the document.

**Comment by romanojd** [comment]
Pull request #298 addresses the rest of this issue.
