### ISSUE TITLE
Acknowledgement Section

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#129]
LS-003 (https://lists.oasis-open.org/archives/openc2-comment/201811/msg00001.html):
> Acknowledgments section needs to have appropriate names (we listed entire TC as of November 5 for csprd01)

**Comment by sparrell** [comment]
I propose we start with the current list in the document (ie the membership list OASIS put in) and 
1) add names of people we remember who contributed but no longer are members (not sure there are any)
2) delete names of members unless they did at least one of the following:
- voted (yes or no, but actually voted) on at least one of LS CSD's
- sent a public review email comment
- attended one of the face2face meetings
- made an edit or a comment in google doc of lang spec
- made a comment or pull request on the GitHub of the lang spec
- contributed to open source related to language spec 
- wrote an email with a comment on LS 
- didn't do any of above but someone (including themselves, ok to add yourself back if you are on delete list) says they remember them contributing something

**Comment by sparrell** [comment]
Per first item in list above add in:

- April Jackson of G2 for voting

**Comment by sparrell** [comment]
Commit https://github.com/oasis-tcs/openc2-oc2ls/commit/bb8a2f44a1be95b2d7e934597f3c5febb0e2985d makes the changes per previous comments

**Comment by romanojd** [comment]
The proposed changed was inadvertently approved and applied prior to concurrence from the LSC committee. We'll keep this issue open until we get concurrence. We can always apply another pull request to make additional updates.

**Comment by romanojd** [comment]
Agreed to accept commit, 2/13/2019 LSC Meeting.
