### ISSUE TITLE
Human Text in Language Spec

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#131]
LS-005 (https://lists.oasis-open.org/archives/openc2-comment/201811/msg00002.html):
> OpenC2 defines  human-intended display text for status messages, etc.
>
> We should make clear that all commands / interactions are in the defined fields and not in the display text. We do not want vendors to break incompatibility by extending meaning into the human-oriented text.
>
> Something like, response of any system should be identical whether or not any human-oriented text is included.

**Comment by jmbrule** [comment]
Agree with the reviewer in this matter.  Need to emphasize that the status text is intended for logging/ debugging and ignored by the openc2 consumer or producer

**Comment by sparrell** [comment]
I'm not sure I understand either the original request or @jmbrule comment.

Is the question whether the 'status text' is specified in our interfaces? I do agree interoperability is a major principle and we should specify exact responses when possible. I thought we did specify what should go in those fields (albeit the details may be in any particular actuator profile, not the LS, when they are not common across all profiles). 

I don't think the text is 'for human display'. It is human readable per our agreement to use human readable fields both to help during the development of the specification and with understanding by new developers trying to use the specification. It is not intended for 'display'.

Wrt to @jmbrule comment 'status text is intended for logging/ debugging', I would maintain that logging and debugging is one use of the status text but NOT the primary use. I disagree that the status text would be 'ignored by the openc2 consumer or producer'. We are trying to design a machine to machine interface that will hopefully evolve to more automation than exists today. The status text field provides information for categorizing different causes of the same status. This categorization may be used by the receiver of the information to automagically do something.

**Comment by jmbrule** [comment]
The status code should be sufficient to unambiguously define what the actuator did upon receipt of the command.  If more granularity is needed, then define more status codes rather than kluge together meaning inferred from the status text

**Comment by TobyConsidine** [comment]
Left out of this is a finer gradation of the HTTP error methodology, wherein error 5.7 may be defined, a system MAY opt to send 500.7.8 as a proprietary message SO LONG AS treating the error AS IF it were 500.7 is a valid response.

Help I'm Under Attack
Help I'm Under Attack...by Martians

(Silly message, and not I did not bother to look up 500.7)

Is this allowed or not? I'm OK with specifically disallowing it.

**Comment by jmbrule** [comment]
The key phrase in @TobyConsidine  is "SO LONG AS treating the error AS IF it were 500.7 ".  I can live with either allowing or not allowing (I lean toward not allow) provided it is treated as if it were the 500.7...

**Comment by romanojd** [comment]
Per F2F, 01/2019, no change necessary, at least not for v1.0. Recommend closing.

**Comment by davaya** [comment]
Same issue, and same comment as #198.

Agree to close.

The intent of "free-form string" is that the content of the string is not, and will not be, standardized. The string can contain much more information than the status code (there is not a 1-1 mapping), but status text is unstructured.

There is no way to write a testable requirement such as "Producers MUST NOT make any decisions based on status text". But the Profile Writer's Guide or OpenC2 Architecture or other committee note shall make clear that if use cases require Producers to take action based on a response, that action shall be based on structured data in the response, not status text.

I disagree with:

> I disagree that the status text would be 'ignored by the openc2 consumer or producer'. We are trying to design a machine to machine interface that will hopefully evolve to more automation than exists today. The status text field provides information for categorizing different causes of the same status. This categorization may be used by the receiver of the information to automagically do something.

As the TC writes additional profiles that evolve toward more automation, our guidance to authors must require that automation to be based on standardized structured data fields in the response, e.g., status subcodes or more complicated but well-defined data structures.

**Comment by romanojd** [comment]
Agreed to close: LSC Meeting, 1/29/2019.
