### ISSUE TITLE
Clarify JADN and OpenC2 relationship

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#135]
LS-009 (https://lists.oasis-open.org/archives/openc2-comment/201811/msg00008.html):
> JADN is referenced throughout the Language spec (12 times, across types and schemas), but is not well defined (somewhat in Annex A).
> 
> It is not a standalone published standard, anyone outside of the OpenC2 TC will likely have never seen before, so seems should be defined/referenced somewhere in the front-matter (Normative References)?

LS-062 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00001.html):
> JADN is widely referenced within the Language Specification document, however, appears to be defined solely by a JADN schema in Annex A.   To understand OpenC2, requires that the implementor first understand JADN, which itself may be a barrier to implementation unless it provides some other compelling advantages, such as code generation from a JADN schema?

**Comment by romanojd** [comment]
Additional CSPRD01 comment [LS-062]:
> Ease of implementation is likely to be a key factor in driving uptake and support of OpenC2. The following are some suggestions for the specs that could help implementers.
> - The Language Specification would benefit from having some examples included. The examples are useful where they have been included in the other two specifications.
> - Having an OpenAPI specification available as a sample would be very helpful. It may not cover all possible use cases for the language, however,  would be useful at least for the RESTful API implementor.  
> - JADN is widely referenced within the Language Specification document, however, appears to be defined solely by a JADN schema in Annex A.   To understand OpenC2, requires that the implementor first understand JADN, which itself may be a barrier to implementation unless it provides some other compelling advantages, such as code generation from a JADN schema?

**Comment by davaya** [comment]
With respect to Issue 168: Section 3.4.3 (Schema Syntax) defines the structure of a JADN schema but contains no background/descriptive text.

Suggest promoting Schema Syntax to a new section 3.5, and adding an introduction:

-----------
### 3.5 Schema Syntax
Sections 3.3 and 3.4 present in table format the schema that defines the structure and constrains the content of OpenC2 messages.  Annex A is the formal definition of that schema in a machine-readable language called JSON Abstract Data Notation (JADN).  Each table in the body of the document directly corresponds to, and is programmatically generated from, a type definition in a JADN schema:

![jadn2md](https://user-images.githubusercontent.com/19152940/50101081-e8705c00-01ef-11e9-9b97-ae240d6078bc.jpg)
**Figure 3-1: JADN type definition in JSON and Markdown table formats**

A JADN schema may include several independently-developed modules, where one module imports type definitions from another.  This section defines the structure of a JADN module. The module consists of two parts - meta-information about the module, and the list of type definitions.

![jadn-struct](https://user-images.githubusercontent.com/19152940/50101224-40a75e00-01f0-11e9-9771-ba3476cddd79.jpg)

**Comment by sparrell** [comment]
There is a JADN-related SLPF public review comment in https://www.oasis-open.org/apps/org/workgroup/openc2-actuator/email/archives/201812/msg00006.html which says

```
The answer to this is somewhat subordinate to the JADN conversation.

As noted elsewhere, there is little useful description of JADN on the web, and the best resource on finding what JADN is and how it works is in the OpenC2 JADN GIT. If JADN were normatively defined elsewhere, then it would have all the normative references, and this specification would incorporate them by reference to the JADN spec. 

As it is, things are somewhat undefined.

The TC could OPT (with appropriate administrative work) to create a normative description of JADN based on current work. This would likely require some time delays to create a JADN TC, which then could receive a donation of all JADN stuff from this TC, and we could reference that specification in flight, with direction to OASIS that we wish that spec to be normative in its final form... (This is similar in some ways to how MQTT came to OASIS)

Or those that want to could firm up the somewhat inchoate JADN material in some other forum, say pushing it into an RFC.  That path is no longer as informal as it once was, and can itself take years...

Not every normatively referenced specification is a formal specification. One of the most frequently referenced works in recent times is the doctoral thesis "Architectural Styles and the Design of Network-based Software Architectures" (Fielding), which defined REST. The problem here is that there does not appear to be any equivalent free-standing document for JADN.

(Anyway, not one that I have successfully found with successive search strings).

If the TC decides it is useful, but it doesn't actually fit, we could opt to put it is a non-normative reference. That does not seem to fit for this, though.

```

**Comment by romanojd** [comment]
We agreed at the January F2F to removed references to JADN from the Language Spec for v1.0. However, JADN will be lost. It will be developed as a standalone specification that a future version of the Language Spec would be able to reference.

Specific changes that will be made to support this decision include:

- Remove Annex A, Schema
- Remove the capability to request a schema from query-features
- Remove specific mentions of "JADN" throughout the spec

**Comment by romanojd** [comment]
This issue is resolved: LSC Meeting, 1/22/2019.

**Comment by davaya** [comment]
Splitting JADN from the LS means:
* Page 6 lines 11-14: "OpenC2 allows the application producing the commands to discover the set of capabilities supported by the managed devices."   This paragraph will not be true until a separate JADN spec is produced and the `query features schema` command is added back into the language spec.  Actuator profiles define conformance requirements for all actuator implementations, but the schema communicates design decisions made for each specific implementation.

**Comment by dlemire60** [comment]
I don't believe we should have predictive language (future versions will ...) in our specification.
