### ISSUE TITLE
Explain Table 3.3.1

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#142]
LS-013 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201811/msg00028.html):

> Page 17, Lines 41-55. The table in Section 3.3.1 describing the OpenC2 command is very sparse, and is the first property table of a large set defining the language. Newcomers to OpenC2 would probably benefit from explanatory language for interpreting the table.

**Comment by jmbrule** [comment]
I see your point, but perhaps we should have the explainatory text in 3.3 (short descript of each column or whatever) then state that it applies to the tables throughout section three?

**Comment by davaya** [comment]
Additional description in pull request #255.

**Comment by romanojd** [comment]
This issues should be resolved by pull request #255.

**Comment by romanojd** [comment]
This issues was already resolved by pull request #255. There were no objections to closing this issue at LSC Meeting, 2/19/2019.
