### ISSUE TITLE
13 editorial comments (173-185)

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#143]
LS-014 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201811/msg00029.html):

> Page 2, Line 7 (and elsewhere): machine-to-machine should be hyphenated pretty much anywhere it appears in this document.
>
> Page 8, Line 36: the example formatted property name (created_at) does not match the Google Doc original.
>
> Page 9, Line 6: the final sentence of the first paragraph is oddly worded. Suggest: The OpenC2 Language Specification and Actuator Profile specifications focus on the language content and meaning at the producer and consumer of the command and response while the transfer specifications focus on the protocols for their exchange.
>
> Page 10, Line 1: References to the subcommittees will be inappropriate as this document progresses through standardization; remove.
>
>Page 12, Line 23: insert comma between "duration' and "etc."
>
> Page 12, Line 27: insert "corresponding" before "profile"
>
> Page 12, Line 38: should "time" be "timing" in "...time, periodicity, duration, ..."?
> 
> Page 12, Line 42: insert "meaningful, whether" before "mandatory to implement"
>
> Page 16, Line 36: the phrase "... appending "." or "." to the type ..." doesn't make sense. Is something missing?
>
> Page 23, Line 12: suggest adding "implementers" before "MUST NOT" for clarity.
>
> Page 23, Line 24: suggest adding "implementers" before "MUST NOT" for clarity.
>
> Page 40, Line 27: the run-on formatting of the example command message makes it hard to read and reduces its utility as an example.
>
> Page 40, Line 39: the run-on formatting of the example response message makes it hard to read and reduces its utility as an example.

**Comment by romanojd** [comment]
The editorial changes, where appropriate, have been depicted in pull request #282.

**Comment by romanojd** [comment]
LSC Meeting, 3/19/2019: There were no objections to applying pull request #282 and closing this issue.
