### ISSUE TITLE
Action example

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#146]
CSDPR01 comment email https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00018.html states:

Page 6 lines 25ish-30ish

I propose adding "(eg Deny)" to  Action definition.

This is issue LS-089 in the [CRM](https://docs.google.com/spreadsheets/d/1zUzGw-w0YDVtyYiK10XBgitIHgCyFdhtllAhSgsRJz0)

**Comment by jmbrule** [comment]
At that point of the document, 'deny' (or any other action for that matter) has not been defined yet, therefore will using it as an example lead to confusion?  Not agreeing or disagreeing with the comment, just asking

**Comment by romanojd** [comment]
I would prefer not to add examples to our definitions section. The official definition should be able to stand on its own. Perhaps, the example could be added later in the document.

I recommend closing this Issue with no change.

**Comment by romanojd** [comment]
LSC Meeting, 2/26/2019: There were no strong opinions either way on this issue. We will leave the addition of the example in Section 1 as suggested.

**Comment by romanojd** [comment]
This Issue is resolved by pull request #270.

**Comment by romanojd** [comment]
LSC Meeting, 3/05/2019: There were no objections to applying pull request #270 and closing this issue.
