### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#149]
CSDPR01 comment email https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00021.html states:

Page 6 lines 25ish-30ish
Please add "OpenC2" as modifier to "message" in Command and Response. 

This is issue LS-092 in the [CRM](https://docs.google.com/spreadsheets/d/1zUzGw-w0YDVtyYiK10XBgitIHgCyFdhtllAhSgsRJz0)

**Comment by jmbrule** [comment]
Will the reviewer offer suggested text?

**Comment by romanojd** [comment]
We previously agreed that by defining special terms _Command_ and _Response_ that we would NOT need to prepend these terms with "OpenC2".

I recommend we close this Issue with no change.

**Comment by romanojd** [comment]
LSC Meeting, 2/26/2019: There were no objections to closing this issue.
