### ISSUE TITLE
Message/Content

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#150]
CSDPR01 comment email https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00022.html states:

```
Page 6 lines 25ish-30ish
Please define message and content since they have specific meanings in later sections.
```

This is issue LS-093 in the [CRM](https://docs.google.com/spreadsheets/d/1zUzGw-w0YDVtyYiK10XBgitIHgCyFdhtllAhSgsRJz0)

**Comment by sparrell** [comment]
https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00046.html added 

`PS I probably should have used action="cancel" instead of action="delete"`

**Comment by jmbrule** [comment]
Agreed, will the reviewer offer up suggested text?

**Comment by romanojd** [comment]
Should we make _Message_ a defined term in Section 1.2?

**Comment by romanojd** [comment]
LSC Meeting, 2/26/2019: I will add _Message_ to the list of defined terms and format it appropriately throughout the document. I expect to have a pull request ready to review at the next LSC Meeting.

**Comment by romanojd** [comment]
Pull request #269 addresses this Issue.

**Comment by romanojd** [comment]
LSC Meeting, 3/05/2019: There were no objections to applying pull request #269 and closing this issue.
