### ISSUE TITLE
DKS07/14: Mandatory to Implement

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#152]
LS-095 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00024.html):

> Pg 12 line 42 “mandatory to implement” replace with “REQUIRED” per section 1.2. ‘Mandatory to implement” is not defined. Use the terms in 1.2 (ie use “required”).

LS-102 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00031.html):

> Pg 32 line 3 “mandatory” - change to “REQUIRED”

**Comment by romanojd** [comment]
Agreed to apply this pull request and close this issue: LSC Meeting, 2/05/2019.
