### ISSUE TITLE
DKS09: What is the purpose of the "jadn:" prefix?

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#154]
Comment LS-097:

> Pg 21 line 6ish-8ish, section 3.3.2 - `jadn:uname`, `jadn:Schema` - why the `jadn:` notation? Aren’t they defined in this spec? I propose the extension format NOT be used inside one specification when referring to a different section of the this specification.

**Comment by davaya** [comment]
As defined in Section 3.4.3, and as described in proposed text for #135, a schema can consist of multiple independently-developed modules.   Type definitions from one schema module can be referenced in another module through the use of an `import` statement (Section 3.4.3.2), and imported definitions are protected from name collisions through use of a namespace prefix (e.g., `jadn:`).

Annex A.1 defines the OpenC2 schema.   Annex A.2 defines the JADN schema, which is referenced in an import statement in A.1.  It would be possible to define JADN inside the OpenC2 schema, but they are logically separate entities, and bundling JADN with OpenC2 would preclude it from being used elsewhere.

Recommend that OpenC2 and JADN schemas remain separate.

As a side note, JADN and actuator profiles such as SLPF are not extensions, they are standardized by the OpenC2 TC and are referenced using the `jadn:` and `slpf:` prefixes.   Extensions are modules, such as Custom Actuator Profiles, that are not part of the OpenC2 suite and are referenced as registered or non-registered extensions using the `extension:` or `extension_unr:` prefixes.

**Comment by romanojd** [comment]
These prefixes will be removed from v1.0 with the resolution of Issue #135.

**Comment by romanojd** [comment]
This issue was closed at LSC Meeting, 1/22/2019.
