### ISSUE TITLE
Number of Profiles

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#155]
LS-098 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00027.html):

> The Specification is inconsistent on the number of profiles an actuator should/must have. I propose the document be written that “All actuators MUST have at least one profile (which can be standard or extension) and MAY have more that one profile”.
> 
> Page 21 line 6ish has cardinality of profile a 0-n. I believe this should be 1..n. Although it may be attempting to cover the case that a profile is not requested, but if discussing the existence of the key ‘profile’ in the request, then it should 0..1 (ie you either ask for the profiles or you don’t). I believe this table is discussing if the profile is in the response, then there should only be one key ‘profile’ with a value with list of 1..n members. Ie the list MUST not be allowed to be an empty list.

**Comment by TobyConsidine** [comment]
Must all profiles have a standard profile, call it the Heartbeat Profile in addition to the whatever usable profiles they have? Is the query "which profiles do you have" part of that standard profile?

I'm not suggesting a big change here, merely suggesting a different way to organize the thoughts on sticking this together.

**Comment by romanojd** [comment]
No objections, per 01/2019 F2F. There could be a "Heartbeat Profile" or something like that, as suggested by @TobyConsidine, but I believe that would be handled outside of and not referenced by the Language Spec.

**Comment by romanojd** [comment]
Brian provided an interesting example that justifies **NOT** requiring Actuators to implement at least one Profile. Brian described an Actuator that starts up without any implemented Profiles, then, at some time later, one or more profiles would be dynamically imported.

There doesn't seem to be a compelling need to require Actuators to implement at least one Profile. Of course, it wouldn't do anything interesting in that state, except for answer 'query features' Commands.

**Comment by romanojd** [comment]
If there are no objections, I recommend closing this issue with no changes.

**Comment by romanojd** [comment]
LSC Meeting, 3/19/2019: There were no objections to closing this issue.
