### ISSUE TITLE
Rules on extending language

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#156]
LS-099 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00028.html):

> Page 22 Line 46ish to page 24 line 27ish - Section 3.3.4
> 
> Section 3.3.3 has very specific rules about what can and can not be extended in the language when importing objects from other specifications. In particular it says:
> > “The OpenC2 Language MAY be extended using imported data objects for TARGET, TARGET_SPECIFIER, ACTUATOR, ACTUATOR_SPECIFIER, ARGUMENTS, and RESULTS. The list of ACTIONS in Section 3.2.1.2 SHALL NOT be extended.” 
> It does not say something equivalent in section 3.3.4 Extensions and there are no conformance statements enforcing the previous sentence.
> 
> I propose sections 3.3.3 and 3.3.4 be combined in a new section 3.3.3 entitled “Extending the OpenC2 Language”, that the new 3.3.3 contain two subsections 3.3.3.1 (consisting of the former 3.3.3) and 3.3.3.2 (consisting of the former 3.3.4), and that the sentence I quoted above appear in 3.3.3 before the two sections and apply to both.
> 
> I will try to put some conformance statements in separate comments.

**Comment by davaya** [comment]
Part of section 3.3.3 "Imported Data" should be moved to a new section 3.1.6 "Imported Data".  That text documents the mechanism by which type definitions from one schema are imported into another schema under a namespace.   That mechanism, like all of section 3.1, describes how schemas are constructed and used, and are independent of OpenC2.

The OpenC2 schema of section 3.3.1 (Command) and 3.3.2 (Response) define places where the language can be extended: 3.3.1.2 (Target), 3.3.1.3 (Actuator), 3.3.1.4 (Args) and 3.3.2 (Response) all have extension and extension_unr fields reserved for Extensions (e.g., Custom Actuator Profiles not standardized by OpenC2).   Target also includes an SLPF namespace as an example of how definitions from a standard Actuator Profile would be imported into Targets, Actuator Specifiers, Args, and Results.

We should decide and clearly document whether **extend** and **extension** includes imports from OpenC2 standard profiles, or only imports from custom profiles (not standardized under the OpenC2 TC) under the extension or extension_unr namespaces.   On one hand, standard profiles are part of the OpenC2 suite of specifications and do not extend OpenC2.  On the other, definitions from standard profiles are imported into the Language Spec and do extend that one spec.

**Comment by romanojd** [comment]
I believe this section has not been re-written to address this Issue.

**Comment by sparrell** [comment]
Pull request #268 is proposed to address this concern

**Comment by romanojd** [comment]
That seems pretty straight forward to me.

**Comment by romanojd** [comment]
I created pull request #285 to replace #268. It is a complete re-write of the "imported types" section that attempts to clarify extensions related to the language.

The main idea is that importing data is really a schema mechanism and is not related to the language definition. We've already tried to eliminate the use of the word "schema" from the document when we removed references to JADN previously. There has been much confusion between importing data and extensions that we've had during meetings. This pull request tries to eliminate this confusion by just focusing on the how one can extend the language.

**Comment by romanojd** [comment]
LSC Meeting, 3/19/2019: There were no objections to applying pull request #285. An amendment was proposed to flatten the namespace syntax to a single delimited name. For example:

**Current:**
```
"target": {
    "slpf": {
        "rule_number": 1234
    }
}
```

**Amendment:**
```
"target": {
    "slpf:rule_number": 1234
}
```

There was an objection to the amendment voiced at the meeting and it was recorded as a comment to the pull request: https://github.com/oasis-tcs/openc2-oc2ls/pull/285#issuecomment-474515315

The commend suggests applying pull request #285 as-is and creating a new issue and pull request to represent the proposed amendment. I think that is the correct approach, especially since there were no objections to the initial pull request. Therefore, I will apply pull request #285, create a new issue to address the proposed amendment, reference the new issue here, and close this issue.

**Comment by romanojd** [comment]
Issue #285 has been applied and issue #287 was created to address the proposed amendment. This issue is now closed.
