### ISSUE TITLE
DKS13: (Section 3.4.3.4) Unknown JADN nomenclature

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#158]
Comment LS-101:

> Pg 30 line 4ish - section 3.4.3.4 `JADN-Type.&2` is this a typo or some notation I didn’t find an explanation of?

**Comment by davaya** [comment]
The .& notation is undocumented in CSDPR01 - it is an option that means "the type of this field is specified by the contents of another field".   STIX uses one object property to define the type of another property all the time, but OpenC2 does not.   JADN type definitions are arrays, not objects, so element 2 of the array (Base Type) is used in lieu of a name to specify what data is present in element 5 (Fields).

All JADN options will be documented in section 3.4.3.12 Option.

**Comment by sparrell** [comment]
Besides adding in what is needed for this, it might help to have another annex with examples on how to read/use JADN.

**Comment by romanojd** [comment]
This issue can be differed to a future version of spec. The schema in question will be removed in v1.0 per the resolution of Issue #135.

**Comment by romanojd** [comment]
This issue was closed at LSC Meeting, 1/22/2018.
