### ISSUE TITLE
Response to mandatory commands

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#160]
LS-103 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00032.html):

> pg 32 lines 11-12, section 4: “an OpenC2 Consumer MUST issue an OpenC2 Response”. As stated a response of “403 Forbidden” or “404 Not Found” would be conformant. Should be worded that consumer must actually return a profile.

**Comment by romanojd** [comment]
No objections, per the F2F, 01/2019.

**Comment by romanojd** [comment]
This issue should be addressed when pull request #267 is applied.

**Comment by romanojd** [comment]
LSC Meeting, 3/19/2019: There were no objections to closing this issue once pull request #267 was applied.
