### ISSUE TITLE
Target Conformance

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#161]
LS-104 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00033.html):

> Page 33, lines 8ish-15ish Section 5.1
> The Specification does not have conformance requirements for fields other than ACTION.
> I propose adding:
> > 3.  MUST include exactly one TARGET-TYPE as specified in Section 3.3.1 and 3.3.1.2

**Comment by jmbrule** [comment]
Agreed, it does state in section 3.3.1 that the target has a cardinality of 1, but that was not reflected in the conformance section

**Comment by romanojd** [comment]
Per F2F, 01/2019, we will add a conformance requirement for the "target" field.

**Comment by romanojd** [comment]
This issue is addressed by pull request #278.

**Comment by romanojd** [comment]
LSC Meeting, 3/12/2019: There were no objections to applying pull request #278 and closing this issue.
