### ISSUE TITLE
Arg Conformance

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#162]
LS-105 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00034.html):

> Page 33, lines 8ish-15ish Section 5.1
> The Specification does not have conformance requirements for fields other than ACTION.
> I propose adding:
> > 4. MAY include Args as specified in Section 3.3.1. If Args is included, the command MUST include exactly one Args as specified in Section 3.3.1 and 3.3.1.4. The Args map MUST contain at least one map item per Section 3.3.1.4 or extensions per sections 3.3.3 or 3.3.4; and all Args map items must be per Section 3.3.1.4 or 3.3.3 or 3.3.4.

**Comment by romanojd** [comment]
Per F2F, 01/2019, we will add a conformance requirement for the "args" field.

**Comment by romanojd** [comment]
This issue is addressed by pull request #278.

**Comment by romanojd** [comment]
LSC Meeting, 3/12/2019: There were no objections to applying pull request #278 and closing this issue.
