### ISSUE TITLE
Actuator Conformance

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#163]
LS-106 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00035.html):

> Page 33, lines 8ish-15ish Section 5.1
> The Specification does not have conformance requirements for fields other than ACTION.
> I propose adding:
> > 5. MAY include Actuator as specified in Section 3.3.1. If Actuator is included, the command MUST include exactly one Actuator as specified in Section 3.3.1 and 3.3.1.3. The Actuator field MUST contain only one item per Section 3.3.1.3 or extensions per sections 3.3.3 or 3.3.4.

**Comment by romanojd** [comment]
Per F2F, 01/2019, we will add a conformance requirement for the "actuator" field.

**Comment by romanojd** [comment]
This issue is addressed by pull request #278.

**Comment by romanojd** [comment]
LSC Meeting, 3/12/2019: There were no objections to applying pull request #278 and closing this issue.
