### ISSUE TITLE
Conformance Numbering

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#164]
LS-107 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00036.html):

> Page 33 lines 9ish to 29ish Section 5 
> My understanding is OASIS would like all conformance statements numbered uniquely. I assume numbered lists inside section numbers is sufficient (but someone should validate that). However there should only be one numbered list in one section. Section 5.1 has two numbered lists. Ie “Secton 5.1 #1" might mean either of 2 statements. Either have more subsections or start the second list at 3.

**Comment by jmbrule** [comment]
In the SLPF I tried to have unique numbering that was of the format
1.2.2 and so on
In the translation we ended up with the subordinate lists being indented rather than delimited with dots. 
We need to be consistent.  I prefer dot delimited but fine with whatever everyone agrees on
1
   2
       1
       2
       ...
    ...
....

**Comment by romanojd** [comment]
This issue is addressed by pull request #278.

**Comment by romanojd** [comment]
LSC Meeting, 3/12/2019: There were no objections to applying pull request #278 and closing this issue.
