### ISSUE TITLE
DKS20: Unmatched bracket cardinality notation in JADN.

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#165]
Comment LS-108:

> JADN uses what I consider a weird notation of unmatched bracket to denote cardinality. Properties tables use notation “0..n” which is explained in section 3.1.3. One example of the wierd JADN notation is
Pg 38 line 36ish in section A.2:
> 
> `[2, "types", "Type", ["]0"], ""]]`
>
> Where is the explanation of this notation? Ie what does “]0” mean? At a minimum it should be explained. I propose it be replaced with the notation used in the property tables

**Comment by davaya** [comment]
As noted in #158, all options will be documented.   The documentation for the min '[' and max ']' options will include the rationale.

> "An open interval does not include its endpoints, and is indicated with parentheses. For example, (0,1) means greater than 0 and less than 1. A closed interval is an interval which includes all its limit points, and is denoted with square brackets. For example, [0,1] means greater than or equal to 0 and less than or equal to 1."

 -- https://en.wikipedia.org/wiki/Interval_(mathematics)

**Comment by sparrell** [comment]
So is the proposal to leave as is with one notation for cardinality in the property tables and a different notation for cardinality in JADN? I think that is confusing and I vote for the property table notation over the JADN notation. Ie change JADN instead of changing the property tables. But if I lose that, then I think you should change the property tables to be consistent.

**Comment by davaya** [comment]
JADN, like JSON Schema, is processed by machine.   JSON Schema defines separate maxItems and minItems validation keywords for array sizes: https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.4.3.  JADN's use of separate min and max values is consistent with JSON schema, and is motivated by simplicity - min and max values are available immediately without the need to define or parse a composite range string syntax.

Tables are processed by humans.  The cardinality of a field displayed for ease of human understanding, and range notation ( '1..n') is widespread and generally understood.   If tables would be more understandable by breaking cardinality out into separate min and max columns it could be done.  But the justification for doing so would be fitness for purpose, not alignment with the machine representation.

If having humans read machine data were a goal, humans would be viewing HTML source and Markdown source, not pages rendered from that data.   JADN is machine data, rendered tables in the language spec are for people.

**Comment by romanojd** [comment]
This issue can be differed to a future version of spec. The schema in question will be removed in v1.0 per the resolution of Issue #135.

**Comment by romanojd** [comment]
This issue was closed at LSC Meeting, 1/22/2018.
