### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#166]
LS-060 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00001.html):
> The Language Specification would benefit from having some examples included. The examples are useful where they have been included in the other two specifications.

**Comment by davaya** [comment]
The language is executed by an actuator.  An actuator that supports functions (such as packet filtering) that are defined in an actuator profile executes the examples given in that profile.

An actuator that supports no profiles conforms to the language spec by supporting just one command: "query features".   Examples of that command and response are shown in the language spec.

The language spec could invent syntactically-valid example commands such as "detonate email_addr" or "cancel uri", but the semantics of, and responses to, such commands would be both undefined and irrelevant to OpenC2 conformance.

Suggest that the language spec refer to actuator profiles for examples relevant to the conformance of OpenC2 producers and consumers.   If hypothetical command examples are provided, they should be caveated with a note that they illustrate potential syntax only, not meaningful behavior or conformance.

**Comment by romanojd** [comment]
LSC Meeting, 3/19/2019: There were no objections to labeling this issue as "editorial".

**Comment by romanojd** [comment]
Many other examples have been added throughout the document to resolve many other issues.
