### ISSUE TITLE
OpenAPI

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#167]
LS-061 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00001.html):
> Having an OpenAPI specification available as a sample would be very helpful. It may not cover all possible use cases for the language, however, would be useful at least for the RESTful API implementor.

**Comment by dlemire60** [comment]
It seems to me incongruent to specify an API for the language, which Toby Considine has characterized as a Platform Independent Model (PIM), as described in issue #132 

I can understand where a vendor might develop an OpenAPI specification for their product, but not for an abstract language.

**Comment by romanojd** [comment]
At F2F, 01/2019, we agreed that this could be a future consideration.

**Comment by romanojd** [comment]
Agreed to close: LSC Meeting, 1/29/2019.
