### ISSUE TITLE
Annex B example alignment

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#169]
LS-085 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00017.html):

> The examples in Annex B and throughout the document need to be aligned with the language specification.

**Comment by romanojd** [comment]
LSC Meeting, 3/19/2019: There were no objections to labeling this issue as "editorial".

**Comment by romanojd** [comment]
Pull request #298 addresses this issue.
