### ISSUE TITLE
property tables need to be aligned with the schema

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#170]
LS-086 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00017.html):

> The property tables in Section 3 need to be aligned with the schema.

**Comment by jmbrule** [comment]
Per the F2F, we will remove the schema in the annex therefore this comment is OBE?  Suggest close

**Comment by romanojd** [comment]
@davaya, what I'd like to do with this is prior to publishing the CSD-candidate draft, we should compare the markdown-formatted property tables in the spec with the markdown-formatted property tables that you generate from JADN to ensure that we are aligned. We should also label a commit of JADN that perfectly aligns with the spec so we know which version is aligned.

**Comment by romanojd** [comment]
Pull request #299 addresses this issue.

**Comment by sparrell** [comment]
Am I missing something? Why is JADN in 1.0? This issue was closed back in Dec-2018  but is today (May-2019) adding JADN file in PR 299.
