### ISSUE TITLE
Acronym Annex

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#171]
LS-087 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00017.html):

> Annex C, Acronyms, needs to be completed

**Comment by romanojd** [comment]
Can somebody volunteer to create the Acronym Annex?

**Comment by jmbrule** [comment]
Jason, I will get it for you.  I just did one for the SLPF so 'warmed up'

**Comment by sparrell** [comment]
I believe this item is candidate for closure if Pull Request #241 is approved

**Comment by romanojd** [comment]
Agreed to merge pull request and close: LSC Meeting, 1/29/2019.
