### ISSUE TITLE
Missing MD ToC

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#172]
LS-088 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00017.html):

> The Table of Contents is missing in the markdown version of the specification.

**Comment by dlemire60** [comment]
Working with OASIS TCADMIN to address this in the publishing process.

**Comment by romanojd** [comment]
Pull request #266 addresses this Issue.

**Comment by romanojd** [comment]
LSC Meeting, 2/26/2019: There were no objections to applying pull request #266 and closing this issue. It is understood that the editors will likely have to update the Table of Contents one more time prior to publishing the document.
