### ISSUE TITLE
Semantics for Common arguments

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#185]
SPPF comment in issue 
https://github.com/oasis-tcs/openc2-apsc-stateless-packet-filter/issues/23 also applies to Language Specification and response should be coordinated (ie can't change SLFP unless LS changes).
Email said:
```

Copy the 'semantics/requirements as the relate to common arguments' of the SLPF to the Language Specification, then in the SLPF simply reference the language specification.

This information applies to common arguments that are defined in the language specification and are likely to be used by multiple actuator profiles. This change will result in more consistent use of arguments

```

**Comment by jmbrule** [comment]
Agreed, if the TC rejects the comment at the Lang spec level, then will have to reject the comment in the slpf. I should have said that this change is subject to a corresponding change in the lang spec

**Comment by dlemire60** [comment]
I support this change to both specifications. We've always anticipated that things identified in APs and then found to be common would eventually get "bubbled up" to the L-Spec. IMO this is a pretty clear case of that.

**Comment by jmbrule** [comment]
I think we accepted this notion during the F2F.  Suggest we incorporate the change then close the issue

**Comment by romanojd** [comment]
Would someone like to propose the change in a pull request?

**Comment by romanojd** [comment]
I will apply the reverse of SLPF pull request 32 (https://github.com/oasis-tcs/openc2-apsc-stateless-packet-filter/pull/32).

**Comment by romanojd** [comment]
Pull request #276 addresses this issue.

**Comment by romanojd** [comment]
LSC Meeting, 3/12/2019: There were no objections to applying pull request #276 and closing this issue.
