### ISSUE TITLE
40-Character Name Restriction

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#188]
LS-015 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 8-30 “All…names and terms are between three and 40 characters long”. This is stated as a Document convention, but reads as a language restriction. Is it intended as a language restriction?

**Comment by jmbrule** [comment]
Agree with the reviewer, we should state it as a language restriction, not a document convention.

**Comment by romanojd** [comment]
If it's not actually normative, I would recommend removing the statement. Leaving it as a non-normative document convention would seem to be confusing.

**Comment by romanojd** [comment]
Unless someone can identify a need for restricting the length of names, I recommend removing the statement by applying pull request #273. If this is a requirement, then we'll need to move it to a normative section somewhere.

**Comment by romanojd** [comment]
LSC Meeting, 3/05/2019: There were no objections to applying pull request #273 and closing this issue.
