### ISSUE TITLE
Normative: "captured or necessary"?

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#192]
LS-019 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 9-34: Is there a normative meaning to the phrase “captured or necessary” Can other information be transmitted? Logs / Sums / Statistics / Ongoing analysis…

**Comment by jmbrule** [comment]
Agree with the reviewer, simply state "Information sent back to the OpenC2 producer as a result of the command".

**Comment by romanojd** [comment]
The proposed change was captured in pull request #270.

**Comment by romanojd** [comment]
LSC Meeting, 3/05/2019: There were no objections to applying pull request #270 and closing this issue.
