### ISSUE TITLE
Authentication Protocols in diagram?

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#193]
LS-020 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 10-26: Are any authentication protocols intended in rectangle on left?

**Comment by jmbrule** [comment]
Would advise against spelling out specific authentication protocols.  Is actually implied with the examples provided (such as ipsec) and auth is derived from c and I

**Comment by romanojd** [comment]
The question was answered. Recommend closing.

**Comment by romanojd** [comment]
LSC Meeting, 3/05/2019: There were no objections to closing this issue.
