### ISSUE TITLE
Rules for Extension

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#194]
LS-021 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 11-35: Consider a section between current 1.7 and 1.8 on Rules for Extension. Alternately, this could be another bullet in the paragraph that ends before. Such rules can affect interoperability, especially when a Producer and intended Consumer may be separated by some sort of message routing or broadcast domain.

LS-022 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 11-38:44 If the specification defines the “set of actions that may be used” then it would appear that extensions are forbidden—yet rules for extension are in scope. Re-work.

LS-080 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00009.html):

> Truth is all schemas are subject to extension and you should write this and your conformance language to specify *conforming* extensions.
> 
> It's not easy making the rules. On one hand, 3.3.3 says: "The list of ACTIONS in Section 3.2.1.2 SHALL NOT be extended." but, then 3.3.4 says: "Organizations may extend the functionality of OpenC2 by defining organization-specific profiles."
> 
> You go onto say: "OpenC2 defines two methods for defining organization-specific profiles: using a registered namespace or an unregistered namespace."
> 
> The first sentence enables an organization to define its own profile, the second sentence says OpenC2 has also defined two ways to extend. So, the limitation on defining more ACTIONS does not apply to the first case.

**Comment by jmbrule** [comment]
The reviewer makes a great point.  The body of the document talks about importing targets and the actuator profiles and states that the actions must come from the table.  Need to modify the 'extensible' bullet to clarify that the language is extensible by importing profiles and/or targets

**Comment by davaya** [comment]
A profile can define new Targets, Actuator Specifiers, Command Arguments and Results.   But for technical reasons it is impossible for a profile to define new Actions.

(The list of actions is a vocabulary (Enumerated), and enumerated items do not include a Type that could be defined in a profile).

**Comment by romanojd** [comment]
Applied pull request #278 added rules for what's extensible. Recommend closing this issue.

**Comment by romanojd** [comment]
LSC Meeting, 3/19/2019: There were no objections to closing this issue.
