### ISSUE TITLE
Difference between "Target" and "Actuator"

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#197]
LS-026 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 12-24 It is unclear what the difference between Target and Actuator is. This MAY be answered in 12-41:51, but the usages seem in conflict (can in conflict with similar language in section 1.6 Overview.

**Comment by jmbrule** [comment]
Not sure how to reword.  The target is what you are doing it to and the actuator is what does it.  Suggest a rewrite?

**Comment by romanojd** [comment]
There were no objections to closing this issue at the LSC Meeting, 2/19/2019.
