### ISSUE TITLE
Purpose of STATUS

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#198]
LS-027 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 13-7: Unclear what “meaning of response means”. Should machine actions / decisions be based solely on the STATUS? Is this for Display only?

**Comment by jmbrule** [comment]
Agree with the reviewer,  should be based on the status code only.  Put another way, the status code and the status text have a one ot one mapping, is the same info

**Comment by romanojd** [comment]
Yes, decisions should be made solely on STATUS, not the STATUS_TEXT.

Does this deserve some kind of requirement? What would that look like?

**Comment by jmbrule** [comment]
Not sure how one would word (or test) such a requirement.  Could add text along the lines that the reviewer suggested (... based solely on text)'

**Comment by romanojd** [comment]
Per F2F, 01/2019, recommend no changes, however, note that "results" are broken down into many parts by datatype.

**Comment by romanojd** [comment]
Agreed to close: LSC Meeting, 1/29/2019.
