### ISSUE TITLE
Consider Report Interactions and Message Types

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#201]
LS-031 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 17-9:10 Message Types:Consider if there are “report” interactions (and message types).
> 
> Reporting has various aspects, from alarms and notifications (tell me if this happens) to logging (write this down and I will ask for some or all of it later) to reporting (track the following bits of information over time and send it to me at defined intervals). For a description of one approach to this, see http://docs.oasis-open.org/energyinterop/ei/v1.0/os/energyinterop-v1.0-os.html#_Toc388604017
> 
> And some associated open source libraries
> http://xpower.xlab.si/unofficial-javadoc-openadr/org/openadr/profile_b/ReportSpecifierType.html
> http://xpower.xlab.si/unofficial-javadoc-openadr/org/openadr/profile_b/SpecifierPayloadType.html
> 
> For another approach to specifying and querying reporting from a remote system, see
> http://docs.oasis-open.org/obix/obix/v1.1/csprd01/obix-v1.1-csprd01.html#_Toc361929131

**Comment by TobyConsidine** [comment]
I think we agreed that all of the standard reporting function belong with responding episodically (https://github.com/oasis-tcs/openc2-oc2ls/issues/219). 

We need to make sure we have a tag to capture all of the post 1.0 functionality.

**Comment by jmbrule** [comment]
suggest post 1.0 and close

**Comment by romanojd** [comment]
I labeled this `future` and recommend closing.

**Comment by romanojd** [comment]
Agreed to close: LSC Meeting, 1/29/2019.
