### ISSUE TITLE
Wording: "specifies an action..."

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#202]
LS-032 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 17-43: Consider “The OpenC2 command specifies an action to be performed by a Target”

**Comment by jmbrule** [comment]
I agree that describes is a less than perfect word, but would rather not use 'specify' because we have attributes that we call 'specifiers' which can lead to confusion.  
Please consider '... defines an action to be performed on a target'

**Comment by romanojd** [comment]
I will change the referenced sentence to read: 
> The OpenC2 Command defines an Action to be performed by a Target.

Recommend close once the change is applied.

**Comment by dlemire60** [comment]
"by" a Target?  I thought Targets were victims in our system, not performers.

**Comment by romanojd** [comment]
There were no objections to making this change at the LSC Meeting, 2/19/2019. Note that a previous change was applied to remove the extra "OpenC2" from terms like _Command_.

**Comment by romanojd** [comment]
Pull request #261 was created to resolve this issue.
