### ISSUE TITLE
Reserves Future Actions

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#203]
LS-034 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 18-45:46 It would seem that the intent here is to “reserve” words for the future to prevent future barriers to interoperability. Recommend that Implementers should be cautioned to avoid these terms or risk that future specifications may invalidate (cause to not interoperate) their work.

LS-077 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00009.html):

> Make this paragraph a note and label as non-normative.
> 
> Reads in part: "The following actions are under consideration for use in future versions of the Language Specification."
> 
> That's a note and non-normative if included at all.

**Comment by jmbrule** [comment]
Per F2F, removing the 'reserved for future' actions

**Comment by romanojd** [comment]
This Issue is addressed by Issue #246 and should be closed at the same time.

**Comment by romanojd** [comment]
LSC Meeting, 2/26/2019: There were no objections to applying pull request #246 and closing this issue.
