### ISSUE TITLE
Action: Investigate

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#204]
LS-035 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 18-41: Investigate. Previous comment on “Reporting” and “Report Specifiers repeated here.
> 
> Reporting has various aspects, from alarms and notifications (tell me if this happens) to logging (write this down and I will ask for some or all of it later) to reporting (track the following bits of information over time and send it to me at defined intervals). For a description of one approach to this, see http://docs.oasis-open.org/energyinterop/ei/v1.0/os/energyinterop-v1.0-os.html#_Toc388604017
> 
> And some associated open source libraries
> http://xpower.xlab.si/unofficial-javadoc-openadr/org/openadr/profile_b/ReportSpecifierType.html
> http://xpower.xlab.si/unofficial-javadoc-openadr/org/openadr/profile_b/SpecifierPayloadType.html
> 
> For another approach to specifying and querying reporting from a remote system, see
> http://docs.oasis-open.org/obix/obix/v1.1/csprd01/obix-v1.1-csprd01.html#_Toc361929131

**Comment by jmbrule** [comment]
Investigate is an effects based action intended for orchestrator to orchestrator commanding.  Investigate implies that the recipient of the command has an analytic capability. 
Suggest close

**Comment by romanojd** [comment]
Agreed to close: LSC Meeting, 1/29/2019.
