### ISSUE TITLE
Action: Remediate

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#205]
LS-036 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 18-43: What is the intent of “remediate” It sounds like it is inviting violation of the directive on status text in 13-6:7. Or is this the purpose” of a command for forensics reasons?

**Comment by jmbrule** [comment]
Investigate, mitigate and remediate were the 'effects' based actions for orchestrator to orchestrator commanding.  
Do not understand the reviewers connection of the remediate action to the text on pg 13 6:7
Suggest close

**Comment by sparrell** [comment]
Isn't this OBE by the decision to remove text after the table (ie remediate will no longer appear in 1.0)?

**Comment by jmbrule** [comment]
Mitigate is gone, investigate and remediate are still there.  I think the F2F removed the 'reserved for future use' bullets on page 18, but the table stayed the same

**Comment by romanojd** [comment]
Agreed to close: LSC Meeting, 1/29/2019.
