### ISSUE TITLE
Extending Conformant Actions

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#206]
LS-037 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 19 7:9 Is there a provision for extending the conformant actions list?

**Comment by jmbrule** [comment]
By design, no.  Did not want everyone and their pet dog cooking up their own actions.  The concern being that we will end up with a lot of different words for very similar actions

**Comment by romanojd** [comment]
There were no objections to closing this issue at LSC Meeting, 2/19/2019.
