### ISSUE TITLE
Profile Registry

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#207]
LS-038 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 19-46: The target slpf is indicated. This is an extension. Is there an extension registry planned? If so is there a prefix for registered/unregistered targets? Is it possible to taget “all SLPF” in a CIDR range?

**Comment by davaya** [comment]
https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201901/msg00003.html addresses the meaning of Extension.   The SLPF namespace refers to a standard actuator profile, not an extension actuator profile.

A namespace registry separate from the language specification is needed; it should be created by the Actuator Profile SC.   It currently would contain one entry (SLPF).  Its scope would include all namespaces used in OpenC2 Targets, Actuator Specifiers, Command Arguments, and Responses.

A command containing an SLPF actuator with no specifiers would be executed by all recipients of the command that support SLPF functions.   The recipients would be designated in the "To" field of a message in a manner supported by the message fabric.  HTTPS does not support multicast to a range of IP addresses.  Pub/Sub supports posting to a channel, and a channel could in theory be established to cover a CIDR range, but this seems like an unclean mixing of network layers.

**Comment by romanojd** [comment]
At the F2F, 01/2019, we agreed that this comment does not affect the Language Spec.

**Comment by romanojd** [comment]
Agreed to close: LSC Meeting, 1/29/2019.
