### ISSUE TITLE
Targets Under Consideration

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#208]
LS-039 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 19-48:20-6. It is unclear what the purpose of this statement is. Should makers of these targets but an “x-“ prefix on each to indicate is an extension but not of the core standard? It seems the intent is not to invalidate any security commands directed towards [disk_partition], but to warn that in future versions they may be a standard profile, and any work before that future MAY not conform to the eventual standard. Does the version number (in the header) handle this, in which case we have created an expectation that one not [disk_partition] without also comparing it to the version… Clarity is required.

LS-075 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00009.html):

> Make this entire paragraph a note and label as non-normative. 3.3.1.2 reads in part: 
> > The following targets are under consideration for use in future versions of the Language Specification.
> 
> Speculations about the future are always notes and hence non-normative.

**Comment by jmbrule** [comment]
Per the Jan 10, 11 2019 F2F, we are pulling the 'future targets' and 'future actions' portions out of the speck.  Suggest removing the referenced text and close

**Comment by romanojd** [comment]
Pull request #265 should resolve this Issue.

**Comment by romanojd** [comment]
LSC Meeting, 2/26/2019: There were not objections to applying pull request #265 and closing this issue.
