### ISSUE TITLE
Clarify "response_requested" Usage Requirements

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#209]
LS-040 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):
> [When response_requested is not explicitly contained in an OpenC2 Command, a Consumer MUST respond in the same manner as
`{"response_requested": "complete"}`.]
>
> 20-38: And that is?...

Note: The text in brackets is an excerpt from the Language Spec.

**Comment by romanojd** [comment]
I think we just need to reword this. The text is just trying to say that `{"response_requested": "complete"}` is implied if it is missing. It's the default case.

**Comment by romanojd** [comment]
It was discussed at F2F, 01/2019, that we need to describe the semantics of each response request type.

**Comment by romanojd** [comment]
Pull request #277 addresses this issue. I changed MUST to SHOULDs. We may want to switch that back. Thoughts?

**Comment by dlemire60** [comment]
I like the PR as is. We've had a lot of push back about requiring responses, so I think SHOULDs are appropriate. New language is much clearer.

**Comment by romanojd** [comment]
LSC Meeting, 3/12/2019: There were no objections to applying pull request #277 and closing this issue.
