### ISSUE TITLE
Behavior of Status Code 301

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#210]
LS-042 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 21:39 Is any particular action expected on a “Moved Permanently” (301). If authorizing to send to a new URI (and not send to this one anymore) does this require any particular level of authorization or trust?

**Comment by romanojd** [comment]
I don't believe anyone has proposed use-cases that would work through the behavior related to this response.

**Comment by jmbrule** [comment]
Agreed, pull the response code from this version and will revisit post 1.0 if a need arises

**Comment by romanojd** [comment]
No object to remove response code 301: F2F, 01/2019.

**Comment by romanojd** [comment]
Agreed to merge pull request and close: LSC Meeting, 1/29/2019.
