### ISSUE TITLE
Imported Data, Extensions

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#211]
LS-079 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00009.html):

> My suggestion is to drop data import altogether since you can't specify it for all cases. How data gets imported is up to users of your specification and then it must meet your requirements. How it got there is anyone's guess.
> 
> We can all appreciate the need to import data but we all must make the choice to normatively provide a method for importing or, simply leave it alone. It's not a good idea to be half-way about it.

LS-043 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 22: Imported data. This is the first discussion of extensions. Should this be called out in the table in 3.3.1.2? Are there specific requirements for the “namespaces” in 10:12. Who is importing? Is this rules for code? Should a generic OpenC2 “watcher” be able to import spaces to log what is going on? Or is this limited namespace collision management?
> 
> Is understanding JADN to understand imports a requirement for conforming Producers and Consumers?

Note: The table in 3.3.1.2 defines the list of targets.

**Comment by davaya** [comment]
Same issue as #212.  See Pull Request https://github.com/oasis-tcs/openc2-oc2ls/pull/240/files.

**Comment by romanojd** [comment]
Closing, per @davaya comment above.
