### ISSUE TITLE
Conforming Extensions

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#213]
LS-045 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 22-44:45 This states requirements for conforming extensions. These should be gathered together either within the document, or with a specific conformance extension for specifications that claim to conform to this specification.
> 
> 23-4:6 This states requirements for conforming extensions. These should be gathered together either within the document, or with a specific conformance extension for specifications that claim to conform to this specification.

**Comment by jmbrule** [comment]
If I understand the reviewer correctly, they are stating that we need to capture the REQUIRED, MUST NOT, MUST etc in the conformance section. If that is the case then +1

**Comment by romanojd** [comment]
Per F2F, 01/2019, we agreed to gather these requirements together in the conformance section, but to also keep these statements here.

**Comment by romanojd** [comment]
LSC Meeting, 3/12/2019: It was discussed that this issue is resolved with pull request #278. There were no objections to applying pull request #278 and closing this issue.
