### ISSUE TITLE
Terminology: "implementations" vs. "consumers"

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#214]
LS-046 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 23-44. “implementations must”. Suggest “Consumers must”

**Comment by davaya** [comment]
Agree, but will be OBE if new extension mechanism is accepted.

**Comment by romanojd** [comment]
In scanning the spec, I noticed that we use "Consumer" and "OpenC2 Consumer" interchangeably and we capitalize "Consumer" inconsistently. I recommend that we always capitalize it because it is a defined term in the spec. 

Question: Should we be more consistent with "OpenC2 Consumer" vs. "Consumer" and which is the preferred term?

**Comment by jmbrule** [comment]
_slight_ preference for 'OpenC2 Consumer' but will not argue for or against eithe

**Comment by dlemire60** [comment]
I'm in favor of consistently capitalizing Consumer (likewise Producer). A quick search shows 30ish instances of "consumer" in the Language Spec. I don't see much value in sticking OpenC2 in front of every one of those. I'd stick with Producer and Consumer. We should also check the other two specifications for consistency on this point.

**Comment by romanojd** [comment]
Agreed to apply this change and close: LSC Meeting, 2/05/2019.

**Comment by romanojd** [comment]
I think I would like to have additional consensus from the LSC Meeting with the consistent application of the format of terms because it was applied to all the terms defined in Section 1.5.

**Comment by dlemire60** [comment]
I would agree that any term we define in Section 1.2 should consistently appear capitalized, unless there's some instance where we use the word in a way that doesn't mean the 1.2 definition.  

Adding Profile makes sense to me. I'm less sure about Argument, as that's a pretty general term and it's not clear that we have any special OpenC2 meaning when we us it.

**Comment by romanojd** [comment]
Agreed to apply pull request #254 and close this issue at 2/12/2019 LSC Meeting.
