### ISSUE TITLE
CIDR Range

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#216]
LS-048 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 23-44:45: What if the target is a bridge, or is a CIDR range? What are the requirements then? There is introduced complexity (to the extent using HTTP headers for “routing”) that should be balanced with the requirements for a router to do something.
>
> See also previous comment on “MUST UNDERSTAND”

**Comment by romanojd** [comment]
This issue will be resolved with Issue #144.

**Comment by sparrell** [comment]
This was discussed at F2F and is discussion is deferred to post 1.0

**Comment by romanojd** [comment]
This issue is resolved: LSC Meeting, 1/22/2019.
