### ISSUE TITLE
Which Targets Support Multiples

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#217]
LS-049 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 25-35:47 
> Does this table support multiples and for which variables? Lists or CIDR for addr? List or range for ports?

**Comment by jmbrule** [comment]
As defined, a command is ONE action and ONE target.  Some single targets (such as CIDR representation of a range of addresses)  represents multiple things, but is still in face a single target.  
The notion of supporting an array of targets in a single command is post 1.0

**Comment by TobyConsidine** [comment]
I almost agree with. I think the multipliciy is fine now, as it need not be defined in the "language", The SLPF happens to be profiled down to a single target. We do not need to bleed between those two notions.

The SLPF MAY need to have an explicity statement that it is so profiled.

**Comment by davaya** [comment]
The concept of a profile is that it *inherits* from the language.   A profile may delete optional items (such as targets) from it's support of the language, and it may define new items (such as slpf-specific targets) but it may not redefine something that is already in the language.

If a future SLPF needed to define a whitelist target (e.g., a bunch of IP addresses that are not in a single CIDR range), it could do so under the slpf namespace.   But it couldn't redefine the ip_addr target to be multiple IP addresses.

**Comment by romanojd** [comment]
I think @jmbrule's comment above summarized it perfectly. Recommend closing this comment.

**Comment by romanojd** [comment]
There were no objections to closing this issue in the LSC Meeting, 2/19/2019.
