### ISSUE TITLE
Standard for Duration

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#218]
LS-050 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 26-40 Consider ISO8601 or its IETF derivative RFC 3339.

LS-051 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 26-45 Consider ISO8601 Duration and related Java class DURATION. Must support granularity down to milliseconds.

**Comment by jmbrule** [comment]
I believe we settled on milliseconds with the logic being that very simple actuators can accommodate integers, more sophisticated actuators can do the translation of the epoch to a string rep of date/time

**Comment by romanojd** [comment]
Per F2F, 01/2019, we agreed to keep the definition of Duration to integer in milliseconds. A more sophisticated representation of Duration can definitely be added when the use-case is justified.

**Comment by romanojd** [comment]
Agreed to close: LSC Meeting, 1/29/2019.
