### ISSUE TITLE
Responding episodically

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#219]
LS-052 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 28-11 Can a system respond with a status episodically, perhaps on a fixed interval (duration)?

**Comment by romanojd** [comment]
We currently do NOT have a response-type that would support episodic status responses.

**Comment by jmbrule** [comment]
This is a post 1.0 issue (we did briefly discuss at F2F)

**Comment by TobyConsidine** [comment]
While I believe we will want to greatly expand this notion, I also am happy with the suggestion that this is pre 1.0.

**Comment by romanojd** [comment]
I labeled this `future` and recommend closing.

**Comment by romanojd** [comment]
Agreed to close: LSC Meeting, 1/29/2019.
