### ISSUE TITLE
Sufficiency of Bounds

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#221]
LS-054 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 29-31:40 Is this a sufficiency of Bounds? Recurrence limitations, max durations, minimum throttle windows, perhaps even more complex (max messages in a duration). Can discuss formal operating constraints in meeting if interest.

**Comment by romanojd** [comment]
The property tables related to the schema will be removed in v1.0 per the resolution of Issue #135.

**Comment by sparrell** [comment]
F2F agreed this is post 1.0 issue

**Comment by romanojd** [comment]
Agreed to close at LSC Meeting, 1/22/2018.
