### ISSUE TITLE
Generic OpenC2 Identifier Type

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#222]
LS-055 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 31-6 Identifier. This is a more general question. Should there be a generic OpenC2 Identifier type sub-typed to Message ID, Command ID, Message/Routing ID, Report Id, etc.? This MAY make bridging and aggregation simpler.

**Comment by romanojd** [comment]
We discussed at the January F2F that the `request_id` in the header and the `command_id` in an OpenC2 Command would use the same datatype. To avoid confusion, we will rename the datatype to something more generic, like `identifier`.

**Comment by romanojd** [comment]
This issue will be resolved with Issue #151.

**Comment by sparrell** [comment]
And issue #151 is resolved with pull request #248

**Comment by romanojd** [comment]
LSC Meeting, 3/12/2019: There were no objections to closing this issue after issue #151 was resolved.
