### ISSUE TITLE
Single dictionary, definition consistency

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#223]
LS-056 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> Section 3.4 Overall: Throughout Section 3.4, terms are defined as used, leading to some duplicate definitions, definition overrides, etc. Suggest overrides, etc. Suggest single dictionary (or a few ones by type), followed by description of messages that use the now pre-defined fields.

**Comment by TobyConsidine** [comment]
As noted in https://github.com/oasis-tcs/openc2-oc2ls/issues/230, words onced defined in the dictionary could be capitalized as per RFC 2119 to indicate thereafter their normative use.

Notice that we can still opt to use whatever capitalization we prefer in actual messages, as RFC2119 is a prose specification only. We just need to make it clear what we are doing in the paragraph in Section 1.

**Comment by davaya** [comment]
Need an example of what change needs to be made to the document.   **All** types defined in section 3.4 "Type Definitions", as well as **all** types defined in Section 3.3 "Content" are normative.   There is no non-normative use of OpenC2-Command (3.3.1), or Artifact (3.4.1.1), or any other type definitions in section 3.4.x.

"Feature" happens to be an English-language word, but where is the ambiguity in the existing text of section 3.4.2.10 defining the Type "Feature" as an Enumerated type?

What is the suggested change to that text?

**Comment by romanojd** [comment]
Per the LSC Meeting, 2/19/2019, we agreed that the changes already applied to the spec that help clarify the definitions addresses this issue. Further, having a glossary, which is actually in our charter, would help, but that would be developed post-1.0.

There were no objections to closing this issue.
