### ISSUE TITLE
Section 4 General Comments

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#224]
LS-057 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> Section 4: reads like an abortive grammar for language. Such a section could be better placed, with other grammar items, in early section 2. Either that, or expand here.

LS-082 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00003.html):

> Complete Section 4. Given the complexity up to this point, I assume 4 consisting of 3 sentences means it is incomplete and the specification cannot proceed until it is completed. Yes?

**Comment by davaya** [comment]
Section 3 defines the syntax of commands and responses.
This section, "Producer - Consumer Interactions, specify how those commands and responses are used to perform OpenC2 operations, and what operations are necessary to claim OpenC2 conformance.

(First sentence of existing section 4 should be deleted - section 3 defines the syntax, and section 5 requires conformance to that syntax.)

**Comment by jmbrule** [comment]
As discussed in the Face to Face, we need to provide additional detail to section 4 (commands).  The only required command is query features, but we do need to put in section four the query features and associated responses, error handling etc.
Unless someone else does it first, I can take a stab after I get some matters with the SLPF addressed.

**Comment by romanojd** [comment]
Pull request is #267 is proposed to address this issue. I think it mostly hits the mark. I would like to discuss it at the next LSC Meeting. If everyone is on board with the approach, I would like to update the wording to make it more consistent with the rest of the Language Spec prior to applying.

**Comment by romanojd** [comment]
LSC Meeting, 3/19/2019: There were no objections to applying pull request #267 and closing this issue.
