### ISSUE TITLE
Conformance Claims

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#225]
LS-058 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> Section 5 (Conformance): The TC rejected a section on specifications that claim conformance here, but then added such clauses in several other locations (pages 22, 23) that do just that. Suggest bringing together in coherent sub-section on conforming derivative specifications here.

~~LS-078 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00009.html):~~

> ~~Serious consideration of what "conformance" means when requiring the use of labels for the interchange of messages needs to be had. This isn't workable.~~
> 
> ~~3.3.1.1 in an unnumbered section: Usage Requirements: says in part:~~
> > ~~"Actions defined external to this section SHALL NOT be used."~~
> 
> ~~Well, that's direct enough but since no actions are defined sufficiently in this section to be useful, that's an odd "SHALL NOT."~~
> 
> ~~Yes? Perhaps only these labels are recognized but even that is different from this requirement.~~

**Comment by TobyConsidine** [comment]
As requested, here is the language that appeared briefly in a previous draft...

5.4 Derivative Specifications and Implementations
The Open Command and Control Language Specification is a general specification and does not take into account the specific restriction and requirements that specific profiles, bindings, and serializations may require. While this specification uses JSON as the model for describing data and message, it does not require the that conforming specifications themselves be in JSON. 
5.4.1 Conformance in Serialization
Specifications that claim conformance to the Open Command and Control Language Specification Version 1.0:
SHALL define a specific mapping of each element to the matching element in the Language Specification. 
SHALL define specific serialization rules for each data type described in 3.1.1. Where available, such serialization MUST be by reference to a common RFC.
SHALL define specific serialization rules for each derived data type described in 3.1.2. The derived data types are defined in specific RFCs, and when compatible with the overall serialization, these RFCs are preferred.
5.4.1 Conformance in Data Model
Specifications that claim conformance to the Open Command and Control Language Specification must follow the following data model rules:
Properties that map directly to this specification SHALL be so identified. If all properties that have the same name map directly to this specification, it MAY include a general statement to conform to this requirements.
If a named Property is an extension the the data elements named in sections 3.1.1 and 3.1.2, that SHALL be so indicated in the specification and its meaning MUST be defined.
5.4.2 Conformance in Cardinality
Each of the Properties described in section 3.4.1 has a cardinality of 1-to-many.  There may be reasons for a Specification claiming conformance to limit Cardinality, for example, to limit the number of targets on a message to one.
Specifications that claim conformance to the Open Command and Control Language Specification SHALL state all Cardinality rules if any are different than in this specification, and MAY offer guidance on redistributing messages that arrive with non-conforming cardinality.

**Comment by jmbrule** [comment]
As discussed in the Face to Face, we need to provide additional detail to section 4 (commands) then reflect in section five (conformance)  The only required command is query features, but we do need to put in section four the query features and associated responses, error handling etc.   
Unless someone else does it first, I can take a stab after I get some matters with the SLPF addressed.

**Comment by romanojd** [comment]
Per F2F, 01/2019, I'm removing LS-078 into a separate issue.

**Comment by romanojd** [comment]
This issue should be addressed when pull request #267  is applied.

**Comment by romanojd** [comment]
LSC Meeting, 3/19/2019: There were no objections to closing this issue once pull request #267 was applied.
