### ISSUE TITLE
Namespace for Actuator

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#226]
LS-073 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00009.html):

> Create a namespace for actuator and resolves internal conflicts on what you do or don't say about it. 3.3, second paragraph, second sentence says: 
> > Other than identification of namespace identifier, the semantics associated with the ACTUATOR specifiers are beyond the scope of this specification.
>
> but, 3.3.1 ID 4, actuator says: 
> > The subject of the action. The actuator executes the action on the target.
> 
> OK, which is it? If all actuator has is a namespace (I didn't see it in this draft), then it can do anything, not only "executes the action on the target." Yes?

**Comment by jmbrule** [comment]
I do not see this as being inconsistent.  We are simply saying that the actuator executes the command, but the semantics associates with actuator specifiers and arguments unique to the actuator is beyond the scope of the lang spec.  Suggest close

**Comment by davaya** [comment]
> Other than identification of namespace identifier, the semantics associated with the ACTUATOR specifiers are beyond the scope of this specification.

Left unsaid, but perhaps it should be said, is that the semantics associated with the ACTUATOR specifiers ARE in scope for the actuator profile referenced by the namespace.   The profile defines the syntax and semantics of those specifiers.  A product/implementation that uses the namespace but does not support the profile is non-conforming.

**Comment by TobyConsidine** [comment]
DO we want to add an appendix on expectations for profile grammar? I recognize this is a bit difficult so long as we have an N=1 to generalize.

**Comment by romanojd** [comment]
How about we change the wording of the first quotation to read: 
> Other than identification of namespace identifier, the semantics associated with the Actuator specifiers are defined in Actuator Profiles.

It's more explicit and I think it avoids the confusion that that commenter had.

**Comment by romanojd** [comment]
There were no objections to making this change at LSC Meeting, 2/20/2019. Pull request #260 was created to resolve this issue.
