### ISSUE TITLE
Terminology: derivation

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#228]
LS-064 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00002.html):

> I would drop the notion of "derivation" as a noise word/concept and simply state the authorities for each data type. For your own identifier, simply state the rule, it isn't "derived from string" unless you are writing a grant proposal. ;)
>
> No derivations, only descriptions. It isn't possible to verify the "derivations" listed in 3.1.2, especially identifier "(TBD rules, e.g., initial alpha followed by alphanumeric or underscore)"

**Comment by davaya** [comment]
Agree.   The listed types are not "derived" from the specified types, they *are* values of the specified types with value and semantic constraints analogous to https://json-schema.org/latest/json-schema-validation.html sections 6.2-6.7 and section 7.

**Comment by jmbrule** [comment]
I agree with the reviewer and subsequent comments, however what is the proposed name for the 3.1.2 heading?  That is, we should change "3.1.2 derived data types" to ??

**Comment by davaya** [comment]
Related to and resolved with #230

**Comment by romanojd** [comment]
This issues should be resolved due to pull request #255.

**Comment by romanojd** [comment]
There were no objections to closing this issue at LSC Meeting, 2/19/2019.
