### ISSUE TITLE
Insert/Correct Cross-References

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#229]
LS-081 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00009.html):

> Insert cross-refs and/or hyperlinks as appropriate on 3.4 and elsewhere. So far as I can tell, there are no cross-refs and/or external links in section 3.4. Assume implementors are reading the text. What's the easiest way for them to obtain the relevant information? Yes.

LS-083 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00009.html):

> Before seeking public reviews in the future, do make serious attempts at all sections before posting for public review.
> 
> The alleged conformance clause reads in part:
> > MUST be structured in accordance with Section 3.4.1, and MUST include exactly one ACTION specified in Section 3.4.1.1.
> 
> If you go look for those sections:
> > 3.4.1 Target Types
> > 3.4.1.1 Artifact
> 
> This is not a serious attempt at a conformance clause and volunteers have spent their time reviewing this non-serious attempt.

LS-070 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00009.html):

> To the editors, no doubt the text is clear and well-organized, to the casual reader, it is not. There should be hyperlinks to further details, when relevant and there should be some type of organization apparent to the reader.
>
> Are the Common message elements further defined elsewhere? The lack of [l]inking makes it difficult to find or say.

LS-063 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00009.html):

> Use http://docs.oasis-open.org/templates/ietf-rfc-list/ietf-rfc-list.html to compare and correct the normative citations.
>
> Sigh, with the production and maintenance of resources such as: [http://docs.oasis-open.org/templates/ietf-rfc-list/ietf-rfc-list.html] it's more than a little disappointing to find incorrect citations of RFCs.
>
> Either the TAB has failed to adequately publicize these aids to editors or being seen, were not read by editors. I'll be gracious and say perhaps they need more publicity.
>
> All of the RFCs that lack DOIs are incorrect. The IETF added those more than a year, possibly two years ago.

**Comment by jmbrule** [comment]
Any volunteers to help Jason cross check the RFC's with the list provided by ietf?  
If nobody steps up, I will cover for you

**Comment by romanojd** [comment]
This requires creating/updating hyperlinks to all the referenced sections within the document.

It will be best to handle this immediately prior to producing and publishing the next CSD-candidate draft. Can the editors be pre-approved to apply these changes at that time?

**Comment by romanojd** [comment]
LSC Meeting, 2/26/2019: There were no objections to addressing this issue just prior to publishing the next CSD-candidate draft. We will leave this Issue open until that is complete.

**Comment by romanojd** [comment]
Pull request #298 addresses this issue.
