### ISSUE TITLE
Labels for JSON Values

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#230]
LS-074 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00009.html):

> Wouldn't it be clearer to say: These are labels for JSON values for the transmission of cybersecurity messages? The values of the labels are not defined but should fall within the semantic field of the label.Â 
> 
> Ex. Seeking donaldhacker@2600PennDC should be labeled as a query (Action), email_addr (Target), Actuator (sys specific)
> 
> There's no shame in being a uniform labeling. That is in and of itself a worthwhile task.
>
> The wording of the "action" terms is confusing. These are labels for "actions" and not actions, such as: "query - Initiate a request for information."
> 
> No, query is a label for an action, when combined with a target label plus value and an undefined actuator, initiates a request for information. It is the undefined actuator and not the query label that makes the request. Yes?

**Comment by davaya** [comment]
It's not clear what text this comment refers to.

However the JADN type definition of OpenC2-Command at section 3.3.1, page 17, lines 41-55 defines a data structure consisting of four fields, the first of which has an ID 1, a name "action" and a type "Action".   When this structure is serialized in the default (human-friendly) flavor of JSON, the structure is an Object containing a Member with the Name "action".   (https://tools.ietf.org/html/rfc7159#section-4).

If "label" is a synonym for "an object member name", then it's value is defined as the literal string "action".   If "label" is a synonym for "an object member", then the member value is defined by the enumerated type Action - it can be only one of the strings listed in the Name column of Section 3.3.1.1.  In no case is the value of the label not defined.

Need clarification for what "These" refers to in "These are labels for JSON values ...".

**Comment by davaya** [comment]
Related Issues #230, #142 require a re-write of Section 3.1, including a description of the type definition format and designation of normative vs. non-normative within type definitions.

**Comment by romanojd** [comment]
Agreed to apply pull request #255 and close this issue at 2/13/2019 LSC Meeting.
