### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#231]
LS-072 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00009.html):

> Move up and restructure around these two items, assuming that is the scope of this draft.
> > The scope of this specification is to define the ACTION and TARGET portions of an OpenC2 command and the common portions of an OpenC2 response.
> 
> If so, why did you wait until 3.3 to declare your scope? Moreover, why not use ACTION and TARGET as organizing principles for the draft?

**Comment by jmbrule** [comment]
The scope was spelled out in section 1.8.  Suggest close

**Comment by romanojd** [comment]
To avoid confusion, let's replace "scope" with "purpose". The point of this sentence is to focus the reader on what they will find in Section 3.3, "Content".

**Comment by romanojd** [comment]
No objections to the proposed change at LSC Meeting, 2/20/2019.

**Comment by romanojd** [comment]
Pull request #259 resolves this issue.
