### ISSUE TITLE
Suggested Terms

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#233]
LS-067 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00002.html):

> Terms like "valid," "information model," "constructed," etc., are vastly overrated. Avoid them unless necessary.
> 
> Try: "The data types used in OpenC2 messages are:" as a model.
>
> With standards, those who write the least, write the best.
>
> Consider: "The syntax of valid OpenC2 messages is defined using an information model constructed from the data types presented here:"
>
> Compare: "The data types used in OpenC2 messages are:"
> 
> BTW, your primitives are defined in XMLSchema part 2. No change necessary but we should all reference and not define data types.

**Comment by jmbrule** [comment]
Suggest closing this issue.  We are doing numerous changes to the spec (associated with making the tables normative, moving JADN to a new spec etc).  Given the lack of specific suggestions for rewording,  I believe the concerns about the use of overrated terms will be adequately resolved (albeit indirectly)

**Comment by davaya** [comment]
Agree to closing the issue by accepting the suggested wording as the baseline for the JADN material in section 3.1: "The data types used in OpenC2 messages are:".

Less is not always more, as other comments have identified missing descriptive text.  But the necessary text should be taut.

**Comment by TobyConsidine** [comment]
Approve of Jason's philosophy even as I recommend closing due to the re-write.

**Comment by romanojd** [comment]
Agreed to close: LSC Meeting, 1/29/2019.

**Comment by davaya** [comment]
Re-write in pull request #255 may address this.

**Comment by romanojd** [comment]
This issues should be resolved by pull request #255.
