### ISSUE TITLE
Format of OpenC2 Response "pairs" field

### ISSUE THREAD

**Issue by bberliner** [oasis-tcs/openc2-oc2ls#235]
LS-110 (https://lists.oasis-open.org/archives/openc2/201901/msg00020.html):

These comments are related to Language Spec PRD-01, page 21 lines 9-10 and page 28 lines 29-37.

At the F2F last week, we had many discussions about the details surrounding the schema required by Commands and Responses in the current draft (09) Language Spec (and the PRD-01 public review spec) and how some of the schema decisions we have made result in a more complicated implementation. One of the first things that every Orchestrator/Producer will do is to ask a Consumer for its capabilities using the `query/features` action/target pair. The current spec returns the supported action/target pairs using a JSON structure that looks like this:
```json
{
	"pairs": [
		[
			"query",
			[
				"features",
				"command"
			]
		],
		[
			"deny",
			[
				"file",
				"uri"
			]
		]
	]
}
```
This example shows a super-simplified response for illustrative purposes. Where it gets tricky is that this data structure is harder to model in code than it needs to be. The `pairs` field is an `Array of Arrays of Pairs of (String, Array of Strings)`. That is particularly hard and error-prone to model for typical JSON tools, like Java with Jackson, for example, since the Array of Pairs is invariant with different types in each element of the Array (first element is a String and next element is an Array of String). Also, the `Arrays of Pairs` part will only ever have a single element, so it’s not really an Array (and it being an Array of Invariants can cause folks to mis-interpret the intent of it requiring exactly those two things and no more).

This response is actually just trying to return the Actions and the list of Targets that each action supports. Starting from that requirement, the following is a much simpler data model and can be easily modeled in code as a Map object, like so:
```json
{
	"pairs": {
		"query": ["features", "commands"],
		"deny": ["file", "uri"]
	}
}
```
 
The `pairs` field becomes a `Map<String, Array<String>>` which is an incredibly easy thing to model in all JSON toolsets.

This issues has been sent to the TC and has received discussion, but my desire is that we have a resolution on this matter before the next Public Review period of the Language Spec.

**Comment by davaya** [comment]
For a comparable presentation, the current structure of the response is:
```
{
	"pairs": [
		["query", ["features", "commands"]],
		["deny", ["file", "uri"]]
	]
}
```
e.g., identical in structural complexity: the value of the "pairs" is a set of members.  The value of each member is a name-value tuple.  The structural difference is that in one case the name and value are separated by a comma and in the other case by a colon.

The difference is the ease with which various tools support collections of arbitrary name-value pairs, i.e., whether the field `Map<String, Array<String>>` has an equivalent `List<Tuple<String, Array<String>>>` construct.

The current Tuple structure was driven by the fact that JADN's vision of Map is a collection where member names are defined and the value type for each name can be different.   Jackson's vision of Map apparently is a collection where member names are arbitrary and all values must be the same type.   JADN is currently neither standardized nor deployed.   Jackson is deployed and well-known by developers.   So it is clear that the burden is upon JADN to become more flexible and accommodate Maps where member names are undefined and member values must all be the same type.

I support changing the structure to that proposed.   Coming up with a Type Definition table that represents the proposed structure will require some thought.

**Comment by bberliner** [comment]
Just to clarify, I use https://jsonlint.com/ to validate my JSON and it reformats it however it does and I copy/paste that. I was not trying to imply anything by the formatting in the comment.

**Comment by davaya** [comment]
I see two ways to achieve the desired result ("pairs" response is a Map, not an Array):
1) create a new JADN MapOf(KeyType, ValueType) built-in datatype.
2) define the pairs response as a Map with the same fields as Action, where each value is Target.*

The second approach is annoying because it violates the DRY principle (https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) by having the same list of actions in two types that must be kept synchronized.

But creating a new JADN type is a far more radical change.  Though it seems like a good addition in the long term, it shouldn't be rushed without lots of thought and testing.

**Comment by romanojd** [comment]
Per the LSC Meeting on 2/19/2019, Dave Kemp agreed to develop a pull request to be presented at the next LSC Meeting.

**Comment by davaya** [comment]
Pull Request #262

**Comment by romanojd** [comment]
There were no objections to applying the pull request and closing this issue at the LSC Meeting, 2/26/2019.
