### ISSUE TITLE
OpenC2 Response "kvps" field Data Type too restrictive

### ISSUE THREAD

**Issue by bberliner** [oasis-tcs/openc2-oc2ls#236]
LS-111 (https://lists.oasis-open.org/archives/openc2/201901/msg00021.html):

These comments are related to Language Spec PRD-01, page 20 lines 53-54 and page 28 lines 22-28.

The current version of the spec has flattened many types of responses in the OpenC2 Response payload, including top-level fields like `strings`, which can hold a generic Array of String and `ints`, which can hold a generic Array of Integers. The spec additionally defines the `kvps` field which can hold a generic Array of Key-Value pairs. The limitation with the schema, however, is that these Key-Value pairs are not really generic key-value pairs as the spec implies, but is limited to Values that are exactly of type `string` (if you look at the definition for the `KVP` type on page 28). This restriction greatly limits what can be returned as a generic key-value pair in a response to be whatever can be serialized into a `string` value. You can see this demonstrated on page 41 of the spec where the example response for a `query/properties` request returns the following:
```json
{
	"status": 200,
	"kvps": [
		["battery_percentage", "0.577216"]
	]
}
```
We see two things happening here. One is that it is actually an `Array of Array of (String, String)`. Which is a bit weird. When most people think about Key-Value pairs in JSON, they are thinking about a `Map<String, Object>`, where the keys are Strings and the values are any other standard JSON thing (a string, an int, an array (startswith ‘[‘) or an object (startswith ‘{‘). As such, most people would expect, in this example, that the `battery_percentage` example would return a Real Number instead of a string, so the “natural” thing that I’d expect to see in `kvps` here would look like this:
```json
{
	"status": 200,
	"kvps": {
		"battery_percentage": 0.577216
	}
}
```
No arrays, just a `Map<String, Object>`, where the Object in this case is Number. A side-effect of changing this from "JSON string" to "JSON object", is that the actuator can return richer data more naturally if desired, like so:
```json
{
	"status": 200,
	"kvps": {
		"battery_percentage": {
			"current": 0.577216,
			"charged_at": 1547506988,
			"status": 12,
			"mode": "high",
			"visible_on_display": true
		}
	}
}
```
Since `kvps` is currently only <String, String>, there is no way to effectively communicate this kind of rich response without adding string serializations to everything (or serializing the JSON sub-objects themselves into Strings and back, which is never desirable). So, I would propose that `kvps` can simply hold a `Map<String, Object` instead of `Array of Array of (String, String)`.

This issue has been submitted to the TC and a discussion has completed around it. My desire is that we have a resolution on this matter before the next Public Review period of the Language Spec.

**Comment by davaya** [comment]
The generic response fields are intended to be exactly that - generic collections of commonly-used types.  In addition to key-value pairs (which is, as noted, actually defined as key-string pairs), there could also be a key-number pairs generic type.

But when the requirement is to craft a response where current is a number and mode is a string and visible is a boolean, that response is not generic, it must be defined in a profile.   If the example response were defined in the SLPF profile, it would not use the generic "kvps" response, it would use the profile-defined "slpf" response:
```
{
	"status": 200,
	"slpf": {
		"battery_percentage": {
			"current": 0.577216,
			"charged_at": 1547506988,
			"status": 12,
			"mode": "high",
			"visible_on_display": true
		}
	}
}
```

**Comment by TobyConsidine** [comment]
I recommend making it entirely generic in the Language Spec, and adding to the conformance section:

"A specification that claims conformance with this specification must clarify and restrict the KVPs in the payload."

**Comment by romanojd** [comment]
Per the LSC Meeting on 2/19/2019, Jason and Brian agreed to work on a pull request to update the definition of `kvps`. This will be presented at the next LSC Meeting.

**Comment by davaya** [comment]
During the LSC meeting there was discussion of "generic" response types including "set of integers", "set of strings" and "set of key-string pairs" (kvps), and it was agreed to delete the integers and strings generic response types, and work on an update to kvps.

During the discussion Toby observed that the generic types could be considered "templates" for what types should look like, as opposed to a definition of a specific type in a table.  Brian suggested using `kvps` to validate an instance that looks like:
```
	"kvps": {
		"battery_percentage": {
			"current": 0.577216,
			"charged_at": 1547506988,
			"status": 12,
			"mode": "high",
			"visible_on_display": true
		}
```
Using Toby's approach, an actuator profile defines the values that can go in a "battery_percentage" type formatted as a set of keys and values, but there is not an actual "kvps" type definition.

A proposal for a generic "kvps" type definition must define how it would be used to validate "battery_percentage" to ensure that something like:
```
	"kvps": {
		"battery_percentage": {
			"current": 0.577216,
			"oil_weight": "10W30",
			"bush_presidency": 43,
			"scrambled_eggs": 5.95
		}
```
will not validate as a legal response.

**Comment by romanojd** [comment]
Pull request #279 addresses this issue. With a more generic results property, we may want to consider removing "ints[]" and "strings[]".

**Comment by dlemire60** [comment]
Did you mean PR #280 ?  279 is the uber-PR to update master from working.

**Comment by romanojd** [comment]
LSC Meeting, 3/19/2019: There were no objections to applying pull request #280 and closing this issue.
