### ISSUE TITLE
Inconsistent use of "extension"

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#242]
LS-109 (https://lists.oasis-open.org/archives/openc2/201901/msg00003.html):

> LS Page 19 Lines 42-46.  The word "extension" is used inconsistently.
> 
> OpenC2 can use both standard actuator profiles and extension (non-standard or custom) actuator profiles.
> 
> The slpf Example Target refers to a standard actuator profile, not a custom actuator profile.
> 
> Change "extensions" to "elements" on page 11 line 50.
> Remove the word "Extension" from page 19 line 46.

**Comment by jmbrule** [comment]
The reviewers point is noted, but the suggested change on page 11 does not address.  The concept that should be conveyed on page 11 line 50 is that elements that are unique to a group of actuators are defined in the profiles and beyond the scope of the language spec.  The suggested wording is not clear in that regard.  Consider "Elements that are unique to and are defined in actuator profiles to extend the language are beyond the scope of this specification".  The suggested wording is "Language elements that are applicable to some actuators..." does not distinguish between elements in the lang spec.  Case in point, the action 'scan' applies to some actuators and is certainly within scope....

**Comment by davaya** [comment]
OpenC2 must be internally consistent with regard to the meaning of the term extension.

If in one section or document an "extension" refers to an actuator profile that is custom (not standardized), then another section or document cannot say that a standard profile is an extension.   A standard profile can define elements that are beyond the scope of the LS.   But those are not extensions because they are included in the body of work of the TC.

**Comment by romanojd** [comment]
Questions from the LSC Meeting, 2/05/2019:
- Does an Actuator Profile _extend_ the OpenC2 language?
- Does it apply differently to "standard" vs. "non-standard" Actuator Profiles?
- What does it mean to "import" a Profile?
- Is there a different mechanism between "standard" and "non-standard" Actuator Profiles?

**Comment by romanojd** [comment]
Agreed to apply pull request #249 and close this issue.
