### ISSUE TITLE
Change Cardinality to Multiplicity

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#244]
LS-112 (https://lists.oasis-open.org/archives/openc2/201901/msg00028.html):

> The terms Cardinality and Multiplicity are often used interchangeably, see for example https://www.uml-diagrams.org/multiplicity.html - "Multiplicity is a definition of cardinality - i.e. number of elements"
>
> However as James Rumbaugh points out, this is technically incorrect.  Cardinality refers to a single number, while multiplicity is "A specification of the range of allowable cardinality values".  (https://martinfowler.com/bliki/MultiplicityNotCardinality.html).
>
> For consistency with UML, wherever OpenC2 refers to a range of cardinalities, it should use the word multiplicity instead.  The type definition tables use the symbol "#" for this range, so this issue requires no change to table headers or contents.

**Comment by davaya** [comment]
Pull Request: https://github.com/oasis-tcs/openc2-oc2ls/pull/245/files

**Comment by romanojd** [comment]
Agreed to apply pull request and close this issue: LSC Meeting, 2/05/2019.
