### ISSUE TITLE
Actuator Terminology

### ISSUE THREAD

**Issue by davaya** [oasis-tcs/openc2-oc2ls#275]
Pull Request #270 added examples to section 1.2 Terminology:
* Action: The task or activity to be performed (e.g., 'deny').
* Actuator: The entity that performs the Action (e.g., 'Stateless Packet Filtering').
* Consumer: A managed device / application that receives Commands. Note that a single device / application can have both Consumer and Producer capabilities.

This highlights the fact that the definition of Actuator is incorrect.
* Consumer is the entity that performs the Action.
* Stateless Packet Filtering is not an entity, it is the name of a function performed by the Consumer.

Fix the definition of actuator to be something like:
* Actuator: The function, as defined in the specified profile, performed by the Consumer (e.g., 'Stateless Packet Filtering').

(*An individual Nikon device, cellphone, or laptop are all entities that could be OpenC2 Consumers.  Each of those entities has a "camera" function.  Actuator is "camera" (the picture-taking function), not a specific entity.*)

**Comment by romanojd** [comment]
LSC Meeting, 3/20/2019: This issue was added to the agenda and discussed. There were no objections with applying the proposed definition change.

**Comment by romanojd** [comment]
The new definition will read:

> * **Actuator**: The function performed by the Consumer that executes the Command (e.g., 'Stateless Packet Filtering').

**Comment by romanojd** [comment]
Pull request #288 addresses this issue.
