### ISSUE TITLE
Fully qualified namespace syntax

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#287]
LSC Meeting, 3/19/2019: There was a proposal to use a fully-qualified namespace syntax instead of the current nested structure. For example:

**Current:**
```
"target": {
    "slpf": {
        "rule_number": 1234
    }
}
```

**Amendment:**
```
"target": {
    "slpf:rule_number": 1234
}
```

**Comment by romanojd** [comment]
Comment copied from #285 from @davaya (https://github.com/oasis-tcs/openc2-oc2ls/pull/285#issuecomment-474515315):

> Looks good to me as is.
> 
> I strongly object to changing the examples as suggested in the meeting, because it is not a scalable approach to extensibility. Brian mentioned the issue of CBOR encoding, suggesting that if the SLPF profile had (for example) 3 targets, they could be assigned:
> 
> ```
>    1024 slpf:rule_number
>    1025 slpf:foo
>    1026 slpf:bar
> ```
> That raises the question of how many CBOR IDs should be assigned to SLPF - if there are 3 targets, and 2 args, and 15 responses, do you reserve the entire 1024-1039 ID space in Target, Args, Specifiers, and Response for SLPF items? What happens when the Battery profile uses 1040-1046, and then SLPF version 1.1 needs another two responses?
> 
> That problem becomes more difficult when there are a dozen, or 100 profiles, each with their own assigned ranges, each of which can evolve beyond version 1.0.
> 
> If there is a suggestion for an approach that accommodates a hundred profiles, each of which can evolve, without requiring all of them to get in each others knickers to avoid collisions, I'm all ears. But for now, assigning one ID and one name to each profile, as in the current version of the language spec and in this Pull Request, seems to be the only approach that is both scalable and serialization-agnostic. I object to changing that approach at the last minute without full consideration of the implications.
> 
> I vote to approve this PR as is. Changing the extension mechanism should be a different issue and PR.
> 
> As an aside, any application can trivially turn any message into a flat JSON object without affecting the property tables:
> 
> ```
> {
>     "action": "deny",
>     "target": {
>         "ipv6_net": {...}
>     },
>     "args": {
>         "slpf": {
>             "direction": "ingress"
>         }
>     }
> }
> ```
> becomes:
> 
> ```
> {
>     "action": "deny",
>     "target:ipv6_net:...": "xyz",
>     "args:slpf:direction": "ingress"
> }
> ```
> The path separator can be anything convenient for the implementation (e.g., dot, slash, backslash, colon) that isn't a valid character in a field name. And any implementation can take the structured message and flatten it at any point in the hierarchy, if that makes it easier for tools to deal with. Full or partial flattening is a local implementation choice that doesn't affect the JSON on the wire.

**Comment by davaya** [comment]
There is a way forward ...

At the Face-To-Face at GWU we discussed the "Flatten" property table option in conjunction with the Artifact target, and decided to remove that option because it might be too confusing to readers.

If we bring back that option, it could be used with any type, not just those imported from another document.  Without flattening, the JSON serialization of a command with Artifact is now:
```
{
  "action": "deny",
  "target": {
    "artifact": {
      "mime_type": "text/markdown",
      "payload": {
        "url": "http://example.com/foo.md"
      }
    }
  }
}
```
If we use the flatten option on the `payload` field, it would be JSON serialized as:
```
{
  "action": "deny",
  "target": {
    "artifact": {
      "mime_type": "text/markdown",
      "payload/url": "http://example.com/foo.md"
      }
    }
  }
}
```
That assumes that we choose slash (/) as the path separator and that character isn't allowed in field Name.  Any non-Name character can be used as the separator.

Serialization rules for other formats would define how they apply the flatten option.

**Comment by romanojd** [comment]
This only confuses things. And it's also another mechanism.

**Comment by romanojd** [comment]
Pull request #296 is a candidate solution to address this issue.

It was interesting to me that the `actuator` property of the Command needs the nested namespace syntax because the namespace identifier is the name of the Actuator. The Actuator Specifiers need to be defined one level down.

I also replaces the results extension to extending the properties of the Response message itself. I was originally thinking that one could just extend the `results` property. That seems more like defining to me since the definition of `results` was very generic. So we're back to extending the properties of the Response.

**Comment by sparrell** [comment]
Wrt "Actuator Specifiers need to be defined one level down" - specifiers are different. In both proposals being discussed for targets, the specifiers are 'further down'. What is under discussion is whether when the target is in another namespace. The choices are 'namespace:target' at the "target" level or "namespace" as the "target" level and the "real" target one level down. In both cases the target specifier is one level beneath the target type - just like in actuator.

**Comment by romanojd** [comment]
LSC Meeting, 3/26/2019: There were no objections to applying pull request #296 and closing this issue.
