### ISSUE TITLE
Update internal type definitions and extensions

### ISSUE THREAD

**Issue by davaya** [oasis-tcs/openc2-oc2ls#291]
SC consensus is that data specified independently of the Language Spec (e.g., Targets, Command Args, Responses defined in actuator profile documents) should be at the same level of nesting as Targets defined within the Language Spec.  That can be accomplished by using the Name of the field that imports a definition as the prefix for imported field names.

Modify the four tables that import profile-defined data to include a "prefix" (or "indent shift-left") option `<`, e.g.:

```
Type: Target (Choice)
+-------+-----------------+-----------------+
|  ID   |       Name      |      Type       |
+-------+-----------------+-----------------+
|    10 |            file | File            |
|    15 | ipv4_connection | IPv4-Connection |
|    17 |        mac_addr | MAC-Addr        |
|  1024 |            slpf | <slpf:Target    | 
| 10001 |          x-acme | <x-acme:Target  |
+-------+-----------------+-----------------+
```
and update JSON serialization rules to include a description of how the option generates commands  using `prefix:target_name`:
```
{
    "action": "deny",
    "target": {
        "slpf:rule_number": 3
    }
}
```
instead of the current:
```
{
    "action": "deny",
    "target": {
        "slpf": {"rule_number": 3}
    }
}
```
*Note: namespace ID is the prefix used in references to imported Types (`slpf:Target`), and field Name `slpf` can be anything (e.g., `filter`).  But by convention the Type nsid is often used verbatim as the field Name.  A different separator could be used in path names to emphasize the difference: pathnames are used in both Language-defined and imported types, while nsids are only used in an imported Type name.*
```
{
    "action": "deny",
    "target": {
        "filter/rule_number": 3
    }
}
```
*The Acme target import highlights another difference - we normally use underscores for field names and dashes for type names, but if we want to use the same string (`x-acme`) for both, then that convention doesn't work.*

Colon could be used as both the pathname and namespace ID separators if the SC prefers to blur the distinction.

**Comment by TobyConsidine** [comment]
I like that this replicates common approaches such as namespace referencing in XSD.

**Comment by romanojd** [comment]
I changed the name of this issue from "Add name prefix for imported data" to "Update internal type definitions and extensions" because it reflected the proposed changes better.

**Comment by romanojd** [comment]
LSC Meeting, 3/26/2019: There were no objections to applying the pull request and closing this issue with the following amendments.

- Remove `<` nomenclature
- Revert definition of Response `profiles` to a single list of NSIDs.
