### ISSUE TITLE
WD02 Review Comment - Response Cardinality

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#32]
As part of the WD02 review process, Dave Lemire commented on section 2.3.1 response structure:
"Do we want to say anything about the cardinality of responses? e.g., "a single command may trigger the return of 0, 1, or multiple responses"?"

Since this is more than an editorial change, this issue is being used for tracking the resolution of this comment

**Comment by sparrell** [comment]
No. The actuator should define it's behavior and provide the answer for all it's cases, not the language spec

**Comment by dlemire60** [comment]
OK. You can close this w/o a document change.

**Comment by sparrell** [comment]
closing as resolved
