### ISSUE TITLE
WD02 Review Comment - Response

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#34]
As part of theWD02 review process, Allan Thomson commented on 3.1.2 OpenC2 Response:

"A OpenC2 Response is a message sent from a recipient of an OpenC2 command message that requires one or more informational elements that provide the requesting system information on the command execution.

All OpenC2 Response messages contain the following mandatory properties:
1) Request Sequence identifier
- This identifier provides the requesting system and responding system with a tracking number that allows them both to connect request/response messages.
- This is an unsigned long number generated by the requestor system where each unique request from that system has a unique number incremented by 1 from the last request
2) Responder Timestamp
- The responding system UTC timestamp (to mSecs granularity) when the response message was created.
3) Response Status Code
- This provides status of the request and response.
- OpenC2 will leverage HTTP response codes.
4) Response Version #
- OpenC2 version information being exchange between requestor and responder. Should match the requestor but not necessary in some use cases.
5) Number of attachments/messages
- By Default a response would include the OpenC2 Response Header and some payload in response to the command. Therefore this number would be 1. But if there are attachments associated with the response then this could be a list of attachment mime types.

Optional properties
1) response update #
- This number is only included when the responder
a) sends fragmented information elements in response to a request. This can occur where either the data for a single request is too large for a single response OR
b) the responder can send asynchronous notifications
2) response update count
- This is only send when there are multiple fragments in response to a single request.
3) Response mime type id
- This identifies the content of the payload outside of the response header in cases where the response may include different content"

This issue is being created to track the resolution of this comment. Note multiple issues are raised so they will be created also and this issue will be used to track the resolution of all the points brought up

**Comment by romanojd** [comment]
All of the suggested information would now be found in "transfer specifications" and not the base "language specification".
