### ISSUE TITLE
OpenC2 Command header field

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#35]
A header property was proposed during the 1/23/2018 Language SC meeting and as a [comment](https://docs.google.com/document/d/1ZK6_2vpC_SsZJnKdEM-gQ335EeHV7iY7yJLZqRLcjio/edit?disco=AAAABoo1ZTk) to oc2ls-v1.0-wd03-0wip.

The following example was provided during the LSC meeting:
```javascript
{
    "header": {
        "command_id": "1234...",
        "version": "1.0",
        "timestamp": "<standard timestamp field when command was created>"
    },
    "action": {},
    "target": {}
}
```

**Comment by romanojd** [comment]
Proposed definition in Section 2.2.1:
**COMMAND_HEADER** (required): Command identifiers, tracking and sequencing information.

**Comment by sparrell** [comment]
at 3/6/18 LSC Looking Glass provided several use cases using header. See https://drive.google.com/drive/folders/1AAAEfUhcjBvJEJCKQIrVSZ6jI2XUbhHL

**Comment by sparrell** [comment]
Header is included now in the LSC
