### ISSUE TITLE
Target Consistency

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#36]
From [comment](https://docs.google.com/document/d/1ZK6_2vpC_SsZJnKdEM-gQ335EeHV7iY7yJLZqRLcjio/edit?disco=AAAABoo1ZUo) to Language Spec from Allan Thompson:

Seems like we use the following inconsistently
- process
- application
- software
- system
- activity
- entity
- network

We should be consistent and clear. 

For example, a network can be restarted/paused/stopped when its a virtual network or an interface on a router that needs to be restarted because of problems.

**Comment by jmbrule** [comment]
A command consists of an action and a target, that is an action by itself is not a complete command.  I do not consider this to be inconsistent, it is merely a case where an action is being put into context of a target.

**Comment by jmbrule** [comment]
This issue is over two years old and has not been commented on for quite some time.  May we close it?

**Comment by dlemire60** [comment]
Since this issue pre-dates the current published CS by over 18 months, I'd support closing it.

**Comment by dlemire60** [comment]
Candidate for closure. @sparrell to open a new issue regarding consistency of terminology and referencing to related standards.
