### ISSUE TITLE
Add entry for honeypots, PF

### ISSUE THREAD

**Issue by alevere** [oasis-tcs/openc2-oc2ls#368]
3.3.1.3 Actuator
Need a number assigned to honeypots such as 1034.

**Comment by alevere** [comment]
Same need for packet filter which is now CSD.

**Comment by dlemire60** [comment]
I believe at this point these are Architecture Spec issues for namespace registry updates. The [current registry](https://github.com/oasis-tcs/openc2-oc2arch/blob/working/namespace-registry.md) includes both honeypots and packet filtering APs. Are we still keeping these in the LS as well?

**Comment by dlemire60** [comment]
appears to be done; registry under architecture; Arch spec needs description of LS / Registry relationship.

Candidate for closure
