### ISSUE TITLE
Clarify Targets "Features" vs. "Properties"

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/openc2-oc2ls#392]
LS v1.0 has the targets `features` and `properties`, with descriptions in the target list (Section 3.3.1.2) that are insufficient to clearly distinguish the intent of each: 

<html>
<body>

ID | Name | Type | # | Description
-- | -- | -- | -- | --
9 | features | Features | 1 | A set of items used with the query Action to determine an Actuator's capabilities.
25 | properties | Properties | 1 | Data attribute associated with an Actuator.

</body>
</html>

The examples in Section 4.2 helps somewhat to clarify `features`; the example in A.3 illustrates a use of `properties` but provide no additional explanation (e.g., where did the `"battery"` property in the example originate?). The LS should provide more informative language that enables the reader to clearly understand how these targets differ and when / how each is appropriate.

EDIT: related issue is #389

**Comment by davaya** [comment]
Features is an enumerated list of the four items in 3.4.2.4: (versions, pairs, profiles, rate_limit), to which schema will be added.  That is the single command that is mandatory for all consumers to support.

Properties is a black hole into which actuator profile editors can dump stuff that they want but don't want to document. (It was created when Efrain was writing a Tesla Powerwall profile, but didn't document what data he could get from the Powerwall.)

My preference is for  Properties to disappear, to be replaced by a requirement for profile editors to create property tables for all Results to be supported by the Consumer.

**Comment by dlemire60** [comment]
Discussed at 8/10 working meeting, and consensus reached on removing properties. @dlemire60 will be preparing a corresponding PR. The PR will address both this issue and #389

**Comment by Vasileios-Mavroeidis** [comment]
Agree with your suggestion to remove the properties target.
