### ISSUE TITLE
Parallel working branches

### ISSUE THREAD

**Issue by davaya** [oasis-tcs/openc2-oc2ls#420]
There are two working branches: "working"  (Sept 28,2023, 167 ahead, 9 behind published) and "working-cs02" (Dec 14, 2022, 166 ahead, 9 behind) that are mostly but not entirely in sync.

This would make sense if we were working in parallel on continued updates to LS v1 and breaking changes to LS v2, bit it's not clear that that is the purpose.  If the next published version will be CS02 with breaking changes, then we should harmonize the working branches to a single branch with commits from both.

**Comment by davaya** [comment]
git log shows only one difference: merge and update README in working vs. "Update oc2ls.md" in working-cs02.

**Comment by dlemire60** [comment]
Agree about harmonizing.  Next version will be **v2.0 CS01**.
