### ISSUE TITLE
CSD01 Ballot Comment - Table 2.1 Required/Optional

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#5]
Table 2.1 has required/optional within the description field. One member suggested making it a column of its own.

**Comment by romanojd** [comment]
This suggestion was considered, but it was proposed to restructure this information from a table to an indented list. That makes this comment OBE. I'll propose the restructured information in a pull request.

**Comment by romanojd** [comment]
Change merged.
