### ISSUE TITLE
JSON Serialization text in section 2.2.1

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#53]
It was proposed to change 2.2.1 from

 `OpenC2 is agnostic of any particular serialization; however, implementations MUST support JSON serialization of the commands.`
 to
 `Implementations MUST support JSON serialization of the commands.`

This raises the issue of alternative serializations on which there is not agreement so this issue was opened to make sure we get around to resolving it.

**Comment by romanojd** [comment]
Agreed to reject comment at 02/27/2018 LSC Meeting: https://meet.lucidmeetings.com/meeting/184673
