### ISSUE TITLE
CSD02 ballot comment - Response

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#55]
Comments were received on csd02 ballot that work should focus on Response

Michael Stair (@mstair)- 
`" progress, need to work on TBD sections (especially Response)"`

Chris Ricard
`"I think some examples of OpenC2 commands and responses could really help in future iterations."`

Allan Thomson
`"Still missing response details"`

Jason Webb
`"The specification is still missing too much data and details for me to be able to see the full picture of this specification and feel comfortable with existing content. I would like to see a full end to end thread, including response details, before I could comfortably vote yes."`

**Comment by romanojd** [comment]
We added response details in Sections 2 and 3 of the Spec. The message contains a minimum set of properties. There were no objections at the 02/27/2018 LSC Meeting: https://meet.lucidmeetings.com/meeting/184673.

- [Section 2.3](https://docs.google.com/document/d/17mLJ0SaK3JjHMbngDIhiuqDLiPx6xgeIknx-LkPWBZQ/edit#bookmark=id.vx1227)
- [Section 3.2.2](https://docs.google.com/document/d/17mLJ0SaK3JjHMbngDIhiuqDLiPx6xgeIknx-LkPWBZQ/edit#bookmark=id.2dlolyb)
