### ISSUE TITLE
CSD02 ballot comment - name spaces, extensibility

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#56]
Comments were made on the csd02 ballot concerning name spaces and extensibility. They are combined in one issue since assuming solution will be same.

John-Mark Gurney
`"3) The lack of name spaces for targets is very concerning. The f2f had an agreement, and that this was not even mentioned in an editorial note is concerning."`

Jason Liu - 
`"Connections/Association­s with other ongoing efforts, such as STIX 2.x COA specifications"`

Paul Patrick
`"The apparent removal of the extensibility mechanisms is something that is not acceptable as it moves the ability for vendors to provide necessary extensions."` 

James Meck
"`The apparent removal of NameSpace, and perhaps unintended and related limiting of Targets to the language spec list, and the lack of Target extensibility, to the apparent exclusion of the use of STIX observables as OpenC2 Targets, even with this our initial spec, is 180s from the F2F straw poll and TC consensus that the STIX observables are fit, and optionally available as optional OpenC2 Target baseline. The removal of language support for an external namespace, the drop of explicit support for [the possibility] of optional Targets (e.g. STIX obervables), in this rev, moves this language spec backwards, not forward. Cannot concur.`"

**Comment by romanojd** [comment]
At 02/27/2018 LSC Meeting, it was agreed to add a section to describe extensibility. A proposal was added to the Spec, although, there were objections to the approach. Kemp, Martinez, and Marian were tasked with resolving their alternate approaches.
https://meet.lucidmeetings.com/meeting/184673

**Comment by sparrell** [comment]
At 3/6/18 LSC Meeting issue #68 was raised and it was stated that #68 had to be resolved before the differing alternative methods of extensibility could be solved

**Comment by sparrell** [comment]
At 3/6/18 LSC meeting Looking Glass provided a STIX extensiblity use case. See https://docs.google.com/document/d/1mMQbC9iP31t6nLuyEwSYrMNHmgK-Y5vLTtnmzje7EJU

**Comment by jmbrule** [comment]
The proposed text for extensibility (refer to comment made by romanojd on 2/27/18) was reworked to address the objections raised.  Suggest resubmitting

**Comment by sparrell** [comment]
addressed in section 2.2.6
