### ISSUE TITLE
CSD02 ballot comment - Faster Progress Desired

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#57]
ballot comments on csd02 included comments we should be moving faster, particularly on material portions of specification

Michelle Barry
`"In agreement with this. I have an overall concern that this approval and progress is taking significantly longer than needed and the focus should be on normative text, versus informative text. Our focus should be on driving value as soon as possible and minimize the delays involved with edits of informative text."`

**Comment by sparrell** [comment]
The new lsc agenda - https://meet.lucidmeetings.com/meeting/184673 - is an attempt to address this issue

**Comment by jmbrule** [comment]
At the risk of overstepping, the standing agenda that the LSC cooked up appears to be effective.  If appropriate, the other subcommittees may want to consider adoption

**Comment by romanojd** [comment]
Since we're close to releasing the specification for public review, I am closing this comment.
