### ISSUE TITLE
CSD02 ballot comment - Implementable/conformance

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#59]
comments on csd02 ballot indicate work is needed to make spec implementable particularly wrt conformance (ie spec must be implementable and have conformance statements consistent that show it via testable statements

Allan Thomson
`"1.2) Still missing lots of details on the actual commands themselves. Nothing is implementable in its current state of specification.
2) Conformance statements are not implementable. (e.g. referring to an actuator profiles that is not defined in a conformance statement is a non-testable statement)
"`

**Comment by romanojd** [comment]
The conformance section has since been added.
