### ISSUE TITLE
CSD01 Ballot Comment - JSON Serialization

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#6]
One member observed the JSON serialization is not defined or referenced. It is mentioned in 2.2.1 but not defined nor referenced where it is defined.

**Comment by romanojd** [comment]
It is mentioned in the conformance section that JSON is the MTI serialization. The syntax is defined in Section 2.2.1. The detailed language definition will be defined with property tables in section 3.
