### ISSUE TITLE
CSD02 Ballot Comments - More work needed

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#60]
this is a catchall issue for the comments on csd02 that more work was needed:

Michael Stair (@mstair)- 
`" progress, need to work on TBD sections (especially Response)"`
Note Response will be handled in a different issue #55

Trey Darley - 
`"Voting yes, with the caveat that this work-in-progress is currently unimplementable and much remains to be defined."`

John-Mark Gurney - 
`"This is a yes, but with reservation. More definition needs to happen on what is currently specified.

1) The new targets are under specified.
2) The base types are not specified. Though simple to define, we need to make sure that we have a good foundation, and not specifying this does not provide a good foundation for going forward.
3) The lack of name spaces for targets is very concerning. The f2f had an agreement, and that this was not even mentioned in an editorial note is concerning."`
note item 3 will be handled in a different issue #56

Jason Liu - 
`"We need to move forward although there is plenty room for improvement. I suggest future revision should include the followings:

- OpenC2 Environment: show entities and the relationships (Orchestrator, Target, Actuator, OpenC2 Proxy, etc.)
- Trust: the trust relationships between the entities, and the authorization methods approved for current and future use
- Connections/Association­s with other ongoing efforts, such as STIX 2.x COA specifications"`
note the last bullet is covered in issue #56

David Hamilton (@dchamilton)
`"The initial lists of targets and actions seem to be acceptable with the group. More detail and content is needed before a vote is really "for" anything. Will there be a syntactic difference between target-specifiers and target-options, for example? If so, why? What is the syntax for a command option/modifier?"`

Allan Thomson
`"1.2) Still missing lots of details on the actual commands themselves. Nothing is implementable in its current state of specification."`

**Comment by romanojd** [comment]
Since most of the missing details have been addressed at this point and we are close to releasing the specification for public review, I am closing this comment.
