### ISSUE TITLE
CSD01 Ballot Comment - Effects-based Actions

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#7]
Observation was made about when 'effects-based command' is first used in section 1 that it doesn't explain what actuator is to be used.

Adjudication:

    add parenthetical "(see Section 2.2.2 on effects-based actions)"

**Comment by romanojd** [comment]
I'll take this.
This was brought up at F2F (2018-01-10). Preference was to remove the term "effects-based actions" until it was defined. I agree. I'll propose the pull request.

**Comment by romanojd** [comment]
Change merged.
