### ISSUE TITLE
Post 1.0 - Interaction of sequence of commands

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#71]
A Looking Glass use case highlights an issue of what to do when two successive commands on one target. The particular example is redirect badurl followed by copy badurl. The intent is to do both but it could be that the second command on a target supercedes the first command. Should there be anything in the language spec on this (or should it be in actuator profile)?

**Comment by jmbrule** [comment]
The issue appears to be that if two commands are sent, but somehow got out of order, then how do we ensure that they are done in the correct order?  If that is the case, then submit that this is an issue that needs to be addressed by the profiles or possibly the ICC.  The language Spec does not identify the 'valid' action target 'pairs' or identify the 'valid actions and targets' for an actuator.  In fact, the same action (and potentially action target pair) may be idempotent for some actuators, or more simply stated, some actuator states of some may be path vector independent while other actuators may require a precise order of commands.  Do not consider it pragmatic to capture this in the LSC.

**Comment by jmbrule** [comment]
This issue is *probably* in the CACOA swim lane.  Suggest closing and perhaps communicate the concern to our colleagues in the other TC.

**Comment by dlemire60** [comment]
I can't locate the use case originally cited in the use cases repo, and I concur with the observations in @jmbrule's two comments. Recommend closing this issue.

**Comment by dlemire60** [comment]
Discussed at triage; superseded by existence of CACAO. Candidate for closure.
