### ISSUE TITLE
Should the language Specification clarify what is to be done if a command can be done by multiple actuators?  

### ISSUE THREAD

**Issue by jmbrule** [oasis-tcs/openc2-oc2ls#74]
The actuator is optional in an OpenC2 command.  The actuator field (with its associated specifiers) identifies to some level of precision the entity(ies) that execute the action on the target. 
The question is:  What do we do in the case where the command is meaningful to multiple actuators of if the actuator field is absent?  
If absent, then any entity that can execute the action SHOULD? MAY? or MUST? execute the command? 
If the actuator field is specified, then should only the entities identified to the degree specified in the actuator field act upon the command?  MAY other actuators act on a command even if the actuator field indicates another?  For example, we have a command "deny, evil domain, stateless-packet-filter",  then should an entity such as a host based firewall act on it?

**Comment by jmbrule** [comment]
BTW, my 'initial reaction' is;  "if you understand the command then act on it" and leave it to the orchestrators and mission managers to limit or expand the distribution of the command

**Comment by sparrell** [comment]
Section 2.2.4 now has "The ACTUATOR field in the command is optional for those cases where the implied actuator(s) areis unambiguous, e.g. at 1:1 mutually-authenticated secure transport link." so that should address the issue
