### ISSUE TITLE
Rules/threads for start_time, stop_time, duration

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#75]
**Allan Thompson:**
>Duration and start/stop time seem mutually exclusive. What are the normative rules defined when start/stop is used vs duration?
>
>For example if someone specifies start/stop and duration where duration conflicts with the difference between stop-start then that would need to be resolved one way or the other. Therefore there needs to be rules on when these parameters are allowed vs not together.
>
>Another example, if you specify duration but not start/stop then does that mean the consumer should start a timer from when the command was received or when the command was created? They could be different times depending on the mechanism used to communicate the command.

**Dave Kemp:**
>The semantics of start/stop/duration need to be specified. We originally had a "frequency" option with which duration made sense - perform this action for 5 minutes every day for a week. Without frequency, duration appears to serve no purpose.
>
>Recommend that duration be deleted unless someone proposes a need with answers to the LG questions.

**Comment by sparrell** [comment]
The semantic of a given actuator should be specified in the actuator profile. It may be only 2 of the 3 exist, or it may the profile says only 2 of the 3 can be used on a given command. It is outside the scope of the language spec to specify the valid combo's.
