### ISSUE TITLE
CSD03 ballot comment - Version

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#86]
Even though version is in HEADER, I believe the version should also be accessible  via a query command as well. The specific use case is when upgrading first one side of an API and then the other. Ie there is a period of time when one side may have capabilities the other side is not yet prepared for, and at least in some (preferably most, if not all) implementations the more advanced side will allow for backwards compatibility - i.e. it can handle more than one, maybe several, versions. The query openc2:version command would return a list of all possible versions the API could operate at, as well as the version it is currently operating at. To allow for this requires the following changes to WD05:

3.3.0.9 Type Name Version
Change Editor’s Note to read
Version appears in an OpenC2 Command Header and in VersionList (see section 2.2.3.3A)

Add 3.3.0.9.a (renumber) Type Name Version_List
Version_List | list | a list of version supported

Add to Section 4 Foundational Actuator Profile
“All OpenC2 consumers MUST support the “action:query” command with  “target” : { “openc2” : version_list}.
See example N.

Add example N to appendix

Changes can be found at https://github.com/sparrell/openc2-oc2ls/commit/899a75dbc32a65101f64c6d7f97e47dcc1048949

**Comment by romanojd** [comment]
**Process Note:**
Your resultant proposed change is against wd05. Now that our update procedures are more advanced, we can say that the working draft is merely a label on the one main file. Then we would propose changes to that one existing file as you've done here. Or we could continue to produce separate files for each working draft, but that will make it more difficult when we have changes against previous versions.

I would probably prefer the former.

**Comment by sparrell** [comment]
resolved
