### ISSUE TITLE
CSD05 Ballot Comment - 3.2.1.4-3.2.1.5 Actuator Specifiers

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#94]
I do not believe this section is sufficiently complete to move forward and must be resolved prior to going to public comment. My minimum requirement for moving forward would be the ability to specify a particular cloud vm in at least several major clouds (eg AWS, Azure, Openstack, ...) such that any profile specification (eg slpf), or custom actuator profile, would specify the same vm the same way. I would find it unacceptable for interworking if sFractal could specify a CAP for the vm using a tuple, some other user/vendor use a string-with-separator, someone else use a list, etc. I forsee a major use of OpenC2 in cloud security so I think this must be solved to go to 1.0. Note it may be solved in AP-SC and language specification just refers to some other spec. I'm ok with that. I'm not ok with current wording of 3.2.1.4-5 which leaves it open and therefore independently extendable different ways.

**Comment by davaya** [comment]
Actuator specifiers are out of scope for the Language Spec.

All actuator specifiers are defined in actuator profiles.  There is currently one actuator profile under ballot, the SLPF.  When a second actuator profile is being developed and it uses vm specifiers in a different manner from the SLPF, then this comment would apply to the second profile.

**Comment by sparrell** [comment]
I disagree with @davaya assertion that "Actuator specifiers are out of scope for the Language Spec".
I agree the some of the 'very specific to a particular kind of actuator' details could be in the actuator profile specification.
I think the 'common to many actuators' specifiers should be in language spec.
I even think the 'very specific to a particular kind of actuator' details for a standardized AP should be in the Language spec but I could be convinced otherwise eventually if data shows it's too burdensome.
We need more data (ie more actuator profiles) to hash out the 'frequency of change' vs 'different AP's using different words for same thing' issues. Right now we don't have too many so I don' think it's a burden to include how to define clouds, a major use of OpenC2 which I predict will apply to almost all AP's we create. Especially since we already argued out how to do it - why take out work we already did?
I agree the language can be extended.
I disagree that other TC specs are 'extensions'. I think if we go to the trouble to standardize an actuator profile then it is ok to put that specific stuff in language spec.

**Comment by dmg2** [comment]
I think that if a vm is the TARGET of an ACTION it should be defined within the actuator profile as a target type. However if the vm contains the actuators which will carry out the ACTION then the matter in which a message is delivered should be carried out in more of a routing form in the message headers, potentially the TO and FROM fields. The format of the TO and FROM fields may need to be better defined in order to allow for this.

**Comment by jmbrule** [comment]
Issue 94, 351 and 352 are essentially the same issue.  One camp would like to move all specifiers, arguments etc 'up' to the language spec and the other camp would like to keep the specifiers, arguments etc that are unique to a particular set of actuators in the profiles.  May we close 94 and 351 and put all the deliberations in 352?  Keeps us from having to repeat the deliberations in multiple threads

**Comment by sparrell** [comment]
I disagree this issue #94 is same issue at #352. This issue would remain here in SLPF even if #352 is rejected. If #352 is agreed to, it only states to agree to what is already in the SLPF.

**Comment by davaya** [comment]
1) it is merely a matter of documentation overhead whether targets, args, and responses defined in an actuator profile are copied to the language spec.  Deciding to copy none, some, or all of them from SLPF does not require or preclude copying none, some, or all of them from the next profile to the LS.  So I take no position on whether it should be done - if it becomes burdensome in the future, then we can stop doing it.

This is analogous to software libraries - if you have a package that defines trig functions,, and a package of linear algebra functions, you can copy their API definitions to another document if you wish.  But whether or not you create an "uber API" document, the definitions don't change. Somebody writing a genome sequencing package can still use the linear algebra package regardless of whether an "uber API" document exists.  If they create a different inner product function and use the same name, or create the same inner product function and give it a different name, that's bad software development practice, but it is neither promoted nor hindered by creating an uber API document
.

**Comment by davaya** [comment]
2. Actuator specifiers cannot be defined by the Language Spec without defining the namespace of the actuator.  A target or arg used by multiple profiles could be referenced from the LS namespace or the defining profile's namespace.  But an actuator specifier always appears under the actuator's namespace.  For that reason I say it is "out of scope" for the LS - the LS could certainly contain a copy the documentation for an SLPF specifier, but an OpenC2 command containing that specifier always names SLPF as the actuator.

**Comment by dlemire60** [comment]
Related to issue #90 ("what is the form of an actuator specifier?")

**Comment by dlemire60** [comment]
Discussed at triage, candidate for closure, longer term process issue regarding AP vs LS location of specifiers
