### ISSUE TITLE
CSD05 Ballot Comment - Conformance - Reorganize

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#95]
Rule 1 of the OASIS Conformance guidelines, http://docs.oasis-open.org/templates/TCHandbook/ConformanceGuidelines.html, states
`"Rule 1: Each conformance clause must clearly identify its conformance target(s), i.e. the type of implementations it applies to"`
I recommend rewording the conformance clauses to refer to OpenC2 Producer or OpenC2 Consumer. Note Rule 3 states:
`"Rule 3: Each Conformance Clause must only concern one type of conformance target, or conformance targets types that are clearly related."`
so separate statements for Producer and Consumer.
Rule 5 states:
`"Rule 5: A Conformance Clause must refer precisely and unambiguously to normative statements and content in the specification main body."`
so I recommend references to sections be included.
I also recommend using the examples in the guidelines - they lump the requirements for a message together in one conformance clause and put each in their own section. Eg Make a seciton 5.1 Conformance Clause 1 - OpenC2 Producer Messages which says "An OpenC2 Producer comforms to this Specification only if (transform current list in section 5 as relates to producer messages and include reference to sections)

**Comment by jmbrule** [comment]
This issue appears to map to one of the pre-version 1.0 drafts.  I believe the format of the current 1.0 specification is in fact consistent with the OASIS guidelines.  Suggest close

**Comment by dlemire60** [comment]
LS v1.0 has been published; this issue has been _de facto_ resolved and should be closed.

**Comment by dlemire60** [comment]
Discussed at triage, candidate for closure.
